const std = @import("std");
const sem = @import("semantic.zig");
const ast_mod = @import("ast.zig");
const type_map = @import("type_map.zig");
const dialect_mod = @import("dialect.zig");
const typed_ast_mod = @import("typed_ast.zig");
const CheckConstraint = ast_mod.CheckConstraint;
const Writer = std.Io.Writer;

pub const Dialect = type_map.Dialect;

pub const Codegen = struct {
    alloc: std.mem.Allocator,
    dialect: Dialect,
    backend: dialect_mod.DialectBackend,

    pub fn init(alloc: std.mem.Allocator, dialect: Dialect) Codegen {
        return .{
            .alloc = alloc,
            .dialect = dialect,
            .backend = dialect_mod.getBackend(dialect),
        };
    }

    // ─── Delegated backend calls ───────────────────────────────

    fn quoteIdent(self: Codegen, w: *Writer, name: []const u8) !void {
        try self.backend.quoteIdent(w, name);
    }

    fn emitCreateDatabase(self: Codegen, w: *Writer, name: []const u8, charset: ?[]const u8) !void {
        try self.backend.emitCreateDatabase(w, name, charset);
    }

    // ─── TypedAst API (sole codegen path) ───────────────────────

    pub fn generateFromTypedAst(self: *Codegen, typed: typed_ast_mod.TypedAst) ![]const u8 {
        var aw = std.Io.Writer.Allocating.init(self.alloc);
        const w = &aw.writer;

        try w.writeAll("-- Generated by zig-typespec\n\n");

        if (typed.schema_name) |name| {
            try self.backend.emitCreateDatabase(w, name, typed.schema_charset);
        }

        // Interleave tables and sql_comments by line number
        var ti: usize = 0;
        var ci: usize = 0;
        while (ti < typed.tables.len or ci < typed.sql_comments.len) {
            const table_line = if (ti < typed.tables.len) typed.tables[ti].line_no else std.math.maxInt(usize);
            const comment_line = if (ci < typed.sql_comments.len) typed.sql_comments[ci].line_no else std.math.maxInt(usize);

            if (comment_line < table_line) {
                try w.writeAll(typed.sql_comments[ci].text);
                try w.writeAll("\n");
                ci += 1;
            } else if (ti < typed.tables.len) {
                try self.generateTypedTable(w, typed.tables[ti]);
                ti += 1;
                if (ti < typed.tables.len or ci < typed.sql_comments.len) {
                    try w.writeAll("\n");
                }
            }
        }

        try w.flush();
        var out = aw.toArrayList();
        return try out.toOwnedSlice(self.alloc);
    }

    pub fn generateSingleTypedTable(self: *Codegen, table: typed_ast_mod.TypedTable) ![]const u8 {
        var aw = std.Io.Writer.Allocating.init(self.alloc);
        const w = &aw.writer;
        try self.generateTypedTable(w, table);
        try w.flush();
        var out = aw.toArrayList();
        return try out.toOwnedSlice(self.alloc);
    }

    fn generateTypedTable(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable) !void {
        try w.writeAll("CREATE TABLE ");
        try self.quoteIdent(w, table.name);
        try w.writeAll(" (\n");

        var needs_comma = false;

        // Columns
        for (table.columns) |col| {
            if (needs_comma) try w.writeAll(",\n");
            needs_comma = true;
            try w.writeAll("  ");
            try self.quoteIdent(w, col.name);
            try w.print(" {s}", .{col.sql_type});

            if (col.unsigned) try self.backend.emitUnsigned(w);

            // NOT NULL (before other modifiers per MySQL convention)
            if (!col.nullable) try w.writeAll(" NOT NULL");

            // Auto-increment (numeric only, not datetime)
            if (col.auto_increment) {
                if (self.dialect == .mysql) {
                    try w.writeAll(" AUTO_INCREMENT");
                } else if (self.dialect == .postgres) {
                    try w.writeAll(" GENERATED ALWAYS AS IDENTITY");
                }
            }

            // Timestamp default (datetime +/++)
            if (col.has_timestamp_default) {
                try self.backend.emitTimestampModifier(w, col.on_update_current_timestamp);
            }

            // PRIMARY KEY
            if (col.primary_key and !(col.auto_increment and self.dialect == .sqlite)) {
                try w.writeAll(" PRIMARY KEY");
            }
            if (col.auto_increment and col.primary_key and self.dialect == .sqlite) {
                try w.writeAll(" PRIMARY KEY AUTOINCREMENT");
            }

            // DEFAULT
            if (col.default) |dv| try emitDefault(w, dv);
            if (col.check) |ck| {
                try w.writeAll(" CHECK (");
                try dialect_mod.emitCheckExpr(w, col.name, ck);
                try w.writeAll(")");
            }
            if (col.comment) |c| {
                if (c.len >= 1 and c[0] == ':' and self.dialect == .mysql) {
                    try w.print(" COMMENT '{s}'", .{std.mem.trim(u8, c[1..], " ")});
                }
            }
            if (col.is_enum and (self.dialect == .postgres or self.dialect == .sqlite)) {
                try w.writeAll(" CHECK (");
                try w.print("\"{s}\" IN (", .{col.name});
                for (col.enum_values, 0..) |v, vi| {
                    if (vi > 0) try w.writeAll(", ");
                    try w.print("'{s}'", .{v});
                }
                try w.writeAll("))");
            }
        }

        // Inline indexes
        for (table.columns) |col| {
            if (col.inline_unique) {
                var dominated = false;
                for (table.indexes) |idx| {
                    if (idx.kind == .unique or idx.kind == .primary_key) {
                        for (idx.fields) |f| { if (std.mem.eql(u8, f, col.name)) { dominated = true; break; } }
                    }
                    if (dominated) break;
                }
                if (!dominated) {
                    if (needs_comma) try w.writeAll(",\n");
                    needs_comma = true;
                    switch (self.dialect) {
                        .mysql => try w.print("  UNIQUE INDEX `uk_{s}` (`{s}`)", .{ col.name, col.name }),
                        .postgres, .sqlite => try w.print("  UNIQUE (\"{s}\")", .{col.name}),
                    }
                }
            }
            if (col.inline_index and self.dialect == .mysql) {
                var dominated = false;
                for (table.indexes) |idx| {
                    for (idx.fields) |f| { if (std.mem.eql(u8, f, col.name)) { dominated = true; break; } }
                    if (dominated) break;
                }
                if (!dominated) {
                    if (needs_comma) try w.writeAll(",\n");
                    needs_comma = true;
                    try w.print("  INDEX `idx_{s}` (`{s}`)", .{ col.name, col.name });
                }
            }
        }

        // Standalone indexes
        for (table.indexes) |idx| {
            try self.backend.emitIndex(w, idx, &needs_comma);
        }

        // FKs
        for (table.fks) |fk| {
            if (needs_comma) try w.writeAll(",\n");
            needs_comma = true;
            try w.writeAll("  FOREIGN KEY (");
            for (fk.fields, 0..) |f, fi| { if (fi > 0) try w.writeAll(", "); try self.quoteIdent(w, f); }
            try w.writeAll(") REFERENCES ");
            try self.quoteIdent(w, fk.ref_table);
            try w.writeAll("(");
            for (fk.ref_fields, 0..) |f, fi| { if (fi > 0) try w.writeAll(", "); try self.quoteIdent(w, f); }
            try w.writeAll(")");
            for (fk.actions) |action| {
                try w.writeAll(" ");
                switch (action.trigger) { .on_delete => try w.writeAll("ON DELETE"), .on_update => try w.writeAll("ON UPDATE") }
                try w.writeAll(" ");
                switch (action.action) { .cascade => try w.writeAll("CASCADE"), .set_null => try w.writeAll("SET NULL") }
            }
        }

        if (needs_comma) try w.writeAll("\n");

        // Footer (dialect-specific)
        switch (self.dialect) {
            .mysql => {
                const charset = table.comment; // unused for footer
                _ = charset;
                const cs = "utf8mb4";
                const engine = table.engine orelse "InnoDB";
                if (table.comment) |c| {
                    const ct = if (c.len >= 1 and c[0] == ':') c[1..] else c;
                    const tr = std.mem.trim(u8, ct, " ");
                    try w.print(") ENGINE={s} DEFAULT CHARSET={s} COMMENT='{s}';\n", .{ engine, cs, tr });
                } else {
                    try w.print(") ENGINE={s} DEFAULT CHARSET={s};\n", .{ engine, cs });
                }
            },
            .postgres, .sqlite => try w.writeAll(");\n"),
        }

        // Comments
        switch (self.dialect) {
            .mysql => {},
            .postgres => {
                if (table.comment) |c| {
                    const ct = if (c.len >= 1 and c[0] == ':') c[1..] else c;
                    const tr = std.mem.trim(u8, ct, " ");
                    if (tr.len > 0) try w.print("COMMENT ON TABLE \"{s}\" IS '{s}';\n", .{ table.name, tr });
                }
                for (table.columns) |col| {
                    if (col.comment) |c| {
                        if (c.len >= 1 and c[0] == ':') {
                            const ct = std.mem.trim(u8, c[1..], " ");
                            if (ct.len > 0) try w.print("COMMENT ON COLUMN \"{s}\".\"{s}\" IS '{s}';\n", .{ table.name, col.name, ct });
                        }
                    }
                }
            },
            .sqlite => {
                if (table.comment) |c| {
                    const ct = if (c.len >= 1 and c[0] == ':') c[1..] else c;
                    const tr = std.mem.trim(u8, ct, " ");
                    if (tr.len > 0) try w.print("-- {s}\n", .{tr});
                }
                for (table.columns) |col| {
                    if (col.comment) |c| {
                        if (c.len >= 1 and c[0] == ':') {
                            const ct = std.mem.trim(u8, c[1..], " ");
                            if (ct.len > 0) try w.print("-- {s}.{s}: {s}\n", .{ table.name, col.name, ct });
                        }
                    }
                }
            },
        }

        // Standalone CREATE INDEX (PG/SQLite)
        if (self.dialect != .mysql) {
            for (table.indexes) |idx| {
                if (idx.kind == .primary_key or idx.kind == .unique or idx.kind == .fulltext) continue;
                try w.writeAll("CREATE INDEX ");
                if (idx.name.len > 0) {
                    try w.print("\"{s}\"", .{idx.name});
                } else {
                    try w.print("\"idx_{s}_{s}\"", .{ table.name, idx.fields[0] });
                }
                try w.print(" ON \"{s}\" (", .{table.name});
                for (idx.fields, 0..) |f, fi| { if (fi > 0) try w.writeAll(", "); try w.print("\"{s}\"", .{f}); }
                try w.writeAll(");\n");
            }
        }
    }

    fn emitDefault(w: *Writer, value: []const u8) !void {
        const is_num_val = blk: {
            _ = std.fmt.parseFloat(f64, value) catch break :blk false;
            break :blk true;
        };
        const is_sql_keyword = std.mem.eql(u8, value, "CURRENT_TIMESTAMP") or
            std.mem.eql(u8, value, "NULL") or
            std.mem.eql(u8, value, "NOW()");
        if (is_num_val or is_sql_keyword) {
            try w.print(" DEFAULT {s}", .{value});
        } else {
            try w.print(" DEFAULT '{s}'", .{value});
        }
    }

    pub fn generateCheckExpr(self: Codegen, w: *Writer, field_name: []const u8, ck: CheckConstraint) !void {
        _ = self;
        try dialect_mod.emitCheckExpr(w, field_name, ck);
    }
};

// ─── Diagnostic ──────────────────────────────────────────────

pub fn diagnosticTrace(sql: []const u8) void {
    std.debug.print("=== [Stage 4: Codegen] ===\n\n", .{});

    var table_count: usize = 0;
    var field_count: usize = 0;
    var fk_count: usize = 0;
    var index_count: usize = 0;

    var line_it = std.mem.splitScalar(u8, sql, '\n');
    while (line_it.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (std.mem.startsWith(u8, trimmed, "CREATE TABLE ")) {
            table_count += 1;
        } else if (trimmed.len > 0 and trimmed[0] == '`' and std.mem.indexOf(u8, trimmed, "PRIMARY KEY") != null) {
            // Skip PRIMARY KEY lines
        } else if (std.mem.indexOf(u8, trimmed, "FOREIGN KEY") != null) {
            fk_count += 1;
        } else if (std.mem.indexOf(u8, trimmed, "INDEX") != null or std.mem.indexOf(u8, trimmed, "UNIQUE INDEX") != null or std.mem.indexOf(u8, trimmed, "FULLTEXT INDEX") != null) {
            index_count += 1;
        }
    }

    var col_it = std.mem.splitScalar(u8, sql, '\n');
    while (col_it.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len > 0 and trimmed[0] == '`') {
            field_count += 1;
        }
    }

    std.debug.print("Tables:    {d}\n", .{table_count});
    std.debug.print("Columns:   {d}\n", .{field_count});
    std.debug.print("FKs:       {d}\n", .{fk_count});
    std.debug.print("Indexes:   {d}\n", .{index_count});
    std.debug.print("SQL lines: {d}\n", .{std.mem.count(u8, sql, "\n") + 1});
    std.debug.print("SQL bytes: {d}\n\n", .{sql.len});
}
