const std = @import("std");
const ast_mod = @import("ast.zig");
const dialect_mod = @import("dialect.zig");
const dialect_enum = @import("dialect_enum.zig");
const typed_ast_mod = @import("typed_ast.zig");
const CheckConstraint = ast_mod.CheckConstraint;
const Writer = std.Io.Writer;

pub const Dialect = dialect_enum.Dialect;

pub const Codegen = struct {
    alloc: std.mem.Allocator,
    dialect: Dialect,
    backend: dialect_mod.DialectBackend,

    pub fn init(alloc: std.mem.Allocator, dialect: Dialect) Codegen {
        return .{
            .alloc = alloc,
            .dialect = dialect,
            .backend = dialect_mod.getBackend(dialect),
        };
    }

    // ─── TypedAst API (sole codegen path) ───────────────────────

    pub fn generateFromTypedAst(self: *Codegen, typed: typed_ast_mod.TypedAst) ![]const u8 {
        var aw = std.Io.Writer.Allocating.init(self.alloc);
        const w = &aw.writer;

        try w.writeAll("-- Generated by zig-typespec\n\n");

        if (typed.schema_name) |name| {
            try self.backend.emitCreateDatabase(w, name, typed.schema_charset);
        }

        // Interleave tables, views, and sql_comments by line number
        var ti: usize = 0;
        var vi: usize = 0;
        var ci: usize = 0;
        while (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
            const table_line = if (ti < typed.tables.len) typed.tables[ti].line_no else std.math.maxInt(usize);
            const view_line = if (vi < typed.views.len) typed.views[vi].line_no else std.math.maxInt(usize);
            const comment_line = if (ci < typed.sql_comments.len) typed.sql_comments[ci].line_no else std.math.maxInt(usize);

            const min_line = @min(table_line, view_line, comment_line);

            if (comment_line == min_line) {
                try w.writeAll(typed.sql_comments[ci].text);
                try w.writeAll("\n");
                ci += 1;
            } else if (view_line == min_line) {
                try self.generateTypedView(w, typed.views[vi]);
                vi += 1;
                if (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
                    try w.writeAll("\n");
                }
            } else if (table_line == min_line) {
                try self.generateTypedTable(w, typed.tables[ti]);
                ti += 1;
                if (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
                    try w.writeAll("\n");
                }
            }
        }

        try w.flush();
        var out = aw.toArrayList();
        return try out.toOwnedSlice(self.alloc);
    }

    pub fn generateSingleTypedTable(self: *Codegen, table: typed_ast_mod.TypedTable) ![]const u8 {
        var aw = std.Io.Writer.Allocating.init(self.alloc);
        const w = &aw.writer;
        try self.generateTypedTable(w, table);
        try w.flush();
        var out = aw.toArrayList();
        return try out.toOwnedSlice(self.alloc);
    }

    /// Emit a full CREATE TABLE statement for one table to the given writer.
    /// Used by both forward codegen (generateFromTypedAst) and migration generation.
    pub fn generateTypedTable(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable) !void {
        try w.writeAll("CREATE TABLE ");
        try self.backend.quoteIdent(w, table.name);
        try w.writeAll(" (\n");

        var needs_comma = false;

        // Columns
        for (table.columns) |col| {
            if (needs_comma) try w.writeAll(",\n");
            needs_comma = true;
            try w.writeAll("  ");
            try self.emitColumnDef(w, col);
        }

        // Inline indexes (delegated entirely to backend)
        for (table.columns) |col| {
            if (col.flags.inline_unique) {
                var dominated = false;
                for (table.indexes) |idx| {
                    if (idx.kind == .unique or idx.kind == .primary_key) {
                        for (idx.fields) |f| {
                            if (std.mem.eql(u8, f, col.name)) {
                                dominated = true;
                                break;
                            }
                        }
                    }
                    if (dominated) break;
                }
                if (!dominated) {
                    try self.backend.emitInlineIndex(w, col.name, true, &needs_comma);
                }
            }
            if (col.flags.inline_index) {
                var dominated = false;
                for (table.indexes) |idx| {
                    for (idx.fields) |f| {
                        if (std.mem.eql(u8, f, col.name)) {
                            dominated = true;
                            break;
                        }
                    }
                    if (dominated) break;
                }
                if (!dominated) {
                    try self.backend.emitInlineIndex(w, col.name, false, &needs_comma);
                }
            }
        }

        // Standalone indexes (via table-level vtable method)
        for (table.indexes) |idx| {
            try self.backend.emitIndex(w, idx, &needs_comma);
        }

        // FKs
        for (table.fks) |fk| {
            if (needs_comma) try w.writeAll(",\n");
            needs_comma = true;
            try w.writeAll("  FOREIGN KEY (");
            for (fk.fields, 0..) |f, fi| {
                if (fi > 0) try w.writeAll(", ");
                try self.backend.quoteIdent(w, f);
            }
            try w.writeAll(") REFERENCES ");
            try self.backend.quoteIdent(w, fk.ref_table);
            try w.writeAll("(");
            for (fk.ref_fields, 0..) |f, fi| {
                if (fi > 0) try w.writeAll(", ");
                try self.backend.quoteIdent(w, f);
            }
            try w.writeAll(")");
            for (fk.actions) |action| {
                try w.writeAll(" ");
                switch (action.trigger) {
                    .on_delete => try w.writeAll("ON DELETE"),
                    .on_update => try w.writeAll("ON UPDATE"),
                }
                try w.writeAll(" ");
                switch (action.action) {
                    .cascade => try w.writeAll("CASCADE"),
                    .set_null => try w.writeAll("SET NULL"),
                }
            }
        }

        if (needs_comma) try w.writeAll("\n");

        // Table footer (delegated to backend)
        try self.backend.emitTableFooter(w, table.engine, null, table.comment);

        // Table and column comments (delegated to backend)
        if (table.comment) |c| {
            try self.backend.emitTableComment(w, table.name, c);
        }
        for (table.columns) |col| {
            if (col.comment) |c| {
                try self.backend.emitColumnComment(w, table.name, col.name, c);
            }
        }

        // TPS type metadata comments for roundtrip preservation (dialect-specific)
        for (table.columns) |col| {
            if (col.tps_type) |tps| {
                try self.backend.emitTpsTypeMetadata(w, col.name, tps);
            }
        }

        // Standalone CREATE INDEX (delegated to backend)
        for (table.indexes) |idx| {
            try self.backend.emitStandaloneIndex(w, table.name, idx);
        }

        // Standalone CREATE INDEX for inline regular indexes (PG/SQLite only)
        // MySQL handles them inline via emitInlineIndex; PG/SQLite emitInlineIndex is no-op for non-unique
        for (table.columns) |col| {
            if (col.flags.inline_index) {
                // Skip if already covered by a standalone index
                var dominated = false;
                for (table.indexes) |idx| {
                    for (idx.fields) |f| {
                        if (std.mem.eql(u8, f, col.name)) {
                            dominated = true;
                            break;
                        }
                    }
                    if (dominated) break;
                }
                if (!dominated) {
                    try self.backend.emitInlineColumnStandaloneIndex(w, table.name, col.name);
                }
            }
        }
    }

    /// Emit a CREATE VIEW statement.
    pub fn generateTypedView(self: Codegen, w: *Writer, view: typed_ast_mod.TypedView) !void {
        try self.backend.emitCreateView(w, view.name, view.query);
        if (view.comment) |c| {
            try self.backend.emitTableComment(w, view.name, c);
        }
    }

    /// Render a single column definition (shared by CREATE TABLE and ALTER TABLE paths).
    /// When skip_name is true, the column name is not emitted (used by PG ALTER COLUMN TYPE).
    pub fn emitColumnDef(self: Codegen, w: *Writer, col: typed_ast_mod.TypedColumn) !void {
        return self.emitColumnDefEx(w, col, false);
    }

    pub fn emitColumnDefEx(self: Codegen, w: *Writer, col: typed_ast_mod.TypedColumn, skip_name: bool) !void {
        if (!skip_name) {
            try self.backend.quoteIdent(w, col.name);
            try w.writeAll(" ");
        }
        try col.sql_type.toSql(self.dialect, w);

        if (col.flags.unsigned) try self.backend.emitUnsigned(w);

        if (!col.flags.nullable) try w.writeAll(" NOT NULL");

        if (col.flags.auto_increment) {
            try self.backend.emitAutoIncrement(w);
        }

        if (col.flags.has_timestamp_default) {
            try self.backend.emitTimestampModifier(w, col.flags.on_update_current_timestamp);
        }

        if (col.flags.primary_key) {
            try self.backend.emitPrimaryKey(w, col.flags.auto_increment);
        }

        if (col.default) |dv| try emitDefault(w, dv);
        if (col.check) |ck| {
            try w.writeAll(" CHECK (");
            try dialect_mod.emitCheckExpr(w, col.name, ck);
            try w.writeAll(")");
        }
        // Inline column comment (MySQL uses COMMENT '...' syntax; PG/SQLite use standalone)
        if (col.comment) |c| {
            try self.backend.emitInlineColumnComment(w, c);
        }
        // Enum type check constraint (PG/SQLite only; MySQL uses native ENUM)
        if (col.flags.is_enum) {
            try self.backend.emitEnumTypeCheck(w, col.name, col.enum_values);
        }
    }

    fn emitDefault(w: *Writer, value: []const u8) !void {
        const is_num_val = blk: {
            _ = std.fmt.parseFloat(f64, value) catch break :blk false;
            break :blk true;
        };
        const is_sql_keyword = std.mem.eql(u8, value, "CURRENT_TIMESTAMP") or
            std.mem.eql(u8, value, "NULL") or
            std.mem.eql(u8, value, "NOW()");
        if (is_num_val or is_sql_keyword) {
            try w.print(" DEFAULT {s}", .{value});
        } else {
            try w.print(" DEFAULT '{s}'", .{value});
        }
    }

    pub fn generateCheckExpr(self: Codegen, w: *Writer, field_name: []const u8, ck: CheckConstraint) !void {
        _ = self;
        try dialect_mod.emitCheckExpr(w, field_name, ck);
    }
};

// ─── Diagnostic ──────────────────────────────────────────────

pub fn diagnosticTrace(sql: []const u8) void {
    std.debug.print("=== [Stage 4: Codegen] ===\n\n", .{});

    var table_count: usize = 0;
    var field_count: usize = 0;
    var fk_count: usize = 0;
    var index_count: usize = 0;

    var line_it = std.mem.splitScalar(u8, sql, '\n');
    while (line_it.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (std.mem.startsWith(u8, trimmed, "CREATE TABLE ")) {
            table_count += 1;
        } else if (trimmed.len > 0 and trimmed[0] == '`' and std.mem.indexOf(u8, trimmed, "PRIMARY KEY") != null) {
            // Skip PRIMARY KEY lines
        } else if (std.mem.indexOf(u8, trimmed, "FOREIGN KEY") != null) {
            fk_count += 1;
        } else if (std.mem.indexOf(u8, trimmed, "INDEX") != null or std.mem.indexOf(u8, trimmed, "UNIQUE INDEX") != null or std.mem.indexOf(u8, trimmed, "FULLTEXT INDEX") != null) {
            index_count += 1;
        }
    }

    var col_it = std.mem.splitScalar(u8, sql, '\n');
    while (col_it.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len > 0 and trimmed[0] == '`') {
            field_count += 1;
        }
    }

    std.debug.print("Tables:    {d}\n", .{table_count});
    std.debug.print("Columns:   {d}\n", .{field_count});
    std.debug.print("FKs:       {d}\n", .{fk_count});
    std.debug.print("Indexes:   {d}\n", .{index_count});
    std.debug.print("SQL lines: {d}\n", .{std.mem.count(u8, sql, "\n") + 1});
    std.debug.print("SQL bytes: {d}\n\n", .{sql.len});
}

// ─── Unit Tests ─────────────────────────────────────────────

const testing = std.testing;

fn makeTestColumn(name: []const u8, sql_type: typed_ast_mod.SqlType) typed_ast_mod.TypedColumn {
    return .{
        .name = name,
        .sql_type = sql_type,
        .flags = .{},
        .default = null,
        .check = null,
        .comment = null,
        .enum_values = &.{},
        .line_no = 1,
    };
}

test "codegen: simple MySQL table" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 2);
    cols[0] = makeTestColumn("id", "int");
    cols[0].flags.primary_key = true;
    cols[0].flags.auto_increment = true;
    cols[1] = makeTestColumn("name", "varchar(32)");
    cols[1].flags.nullable = false;

    const table = typed_ast_mod.TypedTable{
        .name = "user",
        .comment = null,
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .mysql);
    const sql = try cg.generateFromTypedAst(typed);

    try testing.expect(std.mem.indexOf(u8, sql, "CREATE TABLE `user`") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "`id` int") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "AUTO_INCREMENT") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "PRIMARY KEY") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "`name` varchar(32)") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "NOT NULL") != null);
}

test "codegen: PostgreSQL table uses double quotes" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("id", "integer");
    cols[0].flags.primary_key = true;
    cols[0].flags.auto_increment = true;

    const table = typed_ast_mod.TypedTable{
        .name = "user",
        .comment = null,
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .pg);
    const sql = try cg.generateFromTypedAst(typed);

    try testing.expect(std.mem.indexOf(u8, sql, "CREATE TABLE \"user\"") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "GENERATED ALWAYS AS IDENTITY") != null);
    // PG should not have backtick-quoted identifiers
    try testing.expect(std.mem.indexOf(u8, sql, "`") == null);
}

test "codegen: emitColumnDef shared path" {
    const alloc = testing.allocator;
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    const col = makeTestColumn("balance", "decimal(16, 2)");
    col.flags.nullable = false;
    col.flags.unsigned = true;
    col.default = "0";

    var cg = Codegen.init(alloc, .mysql);
    try cg.emitColumnDef(w, col);
    try w.flush();

    var out = aw.toArrayList();
    const result = try out.toOwnedSlice(alloc);

    try testing.expect(std.mem.indexOf(u8, result, "`balance`") != null);
    try testing.expect(std.mem.indexOf(u8, result, "decimal(16, 2)") != null);
    try testing.expect(std.mem.indexOf(u8, result, "UNSIGNED") != null);
    try testing.expect(std.mem.indexOf(u8, result, "NOT NULL") != null);
    try testing.expect(std.mem.indexOf(u8, result, "DEFAULT 0") != null);
}

test "codegen: emitColumnDef PG omits UNSIGNED" {
    const alloc = testing.allocator;
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    const col = makeTestColumn("count", "integer");
    col.flags.unsigned = true;

    var cg = Codegen.init(alloc, .pg);
    try cg.emitColumnDef(w, col);
    try w.flush();

    var out = aw.toArrayList();
    const result = try out.toOwnedSlice(alloc);

    try testing.expect(std.mem.indexOf(u8, result, "UNSIGNED") == null);
    try testing.expect(std.mem.indexOf(u8, result, "\"count\"") != null);
}

// ─── Additional codegen dialect tests ────────────────────────────

test "codegen: SQLite AUTOINCREMENT in PRIMARY KEY" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("id", "INTEGER");
    cols[0].flags.primary_key = true;
    cols[0].flags.auto_increment = true;

    const table = typed_ast_mod.TypedTable{
        .name = "item",
        .comment = null,
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .sqlite);
    const sql = try cg.generateFromTypedAst(typed);

    try testing.expect(std.mem.indexOf(u8, sql, "PRIMARY KEY AUTOINCREMENT") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "\"item\"") != null);
}

test "codegen: PG standalone COMMENT ON TABLE" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("id", "integer");
    cols[0].flags.primary_key = true;

    const table = typed_ast_mod.TypedTable{
        .name = "users",
        .comment = "User accounts",
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .pg);
    const sql = try cg.generateFromTypedAst(typed);

    try testing.expect(std.mem.indexOf(u8, sql, "COMMENT ON TABLE") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "'User accounts'") != null);
}

test "codegen: SQLite COMMENT uses -- style" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("id", "INTEGER");
    cols[0].flags.primary_key = true;

    const table = typed_ast_mod.TypedTable{
        .name = "logs",
        .comment = "Log entries",
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .sqlite);
    const sql = try cg.generateFromTypedAst(typed);

    try testing.expect(std.mem.indexOf(u8, sql, "-- Log entries") != null);
    // SQLite should NOT have COMMENT ON
    try testing.expect(std.mem.indexOf(u8, sql, "COMMENT ON") == null);
}

test "codegen: check expression BETWEEN" {
    const alloc = testing.allocator;
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    var cg = Codegen.init(alloc, .mysql);
    try cg.emitCheckExpr(w, "age", .{ .kind = .range, .expr = "0,150", .line_no = 1 });
    try w.flush();

    var out = aw.toArrayList();
    const result = try out.toOwnedSlice(alloc);

    try testing.expect(std.mem.indexOf(u8, result, "age BETWEEN 0 AND 150") != null);
}

test "codegen: check expression IN list" {
    const alloc = testing.allocator;
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    var cg = Codegen.init(alloc, .mysql);
    try cg.emitCheckExpr(w, "status", .{ .kind = .in_list, .expr = "'active','inactive','banned'", .line_no = 1 });
    try w.flush();

    var out = aw.toArrayList();
    const result = try out.toOwnedSlice(alloc);

    try testing.expect(std.mem.indexOf(u8, result, "status IN (") != null);
    try testing.expect(std.mem.indexOf(u8, result, "'active'") != null);
}

test "codegen: PG uses double quotes, no backticks" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 2);
    cols[0] = makeTestColumn("id", "serial");
    cols[0].flags.primary_key = true;
    cols[1] = makeTestColumn("order", "text");

    const table = typed_ast_mod.TypedTable{
        .name = "items",
        .comment = null,
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .pg);
    const sql = try cg.generateFromTypedAst(typed);

    try testing.expect(std.mem.indexOf(u8, sql, "\"items\"") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "\"order\"") != null);
    // No backticks in PG output
    try testing.expect(std.mem.indexOf(u8, sql, "`") == null);
}

test "codegen: MySQL ENGINE in table footer" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("id", "int");
    cols[0].flags.primary_key = true;

    const table = typed_ast_mod.TypedTable{
        .name = "t",
        .comment = null,
        .engine = "MyISAM",
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .mysql);
    const sql = try cg.generateFromTypedAst(typed);

    try testing.expect(std.mem.indexOf(u8, sql, "ENGINE=MyISAM") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "DEFAULT CHARSET=utf8mb4") != null);
}

test "codegen: MySQL UNSIGNED column" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("amount", "int");
    cols[0].flags.unsigned = true;

    const table = typed_ast_mod.TypedTable{
        .name = "t",
        .comment = null,
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .mysql);
    const sql = try cg.generateFromTypedAst(typed);
    try testing.expect(std.mem.indexOf(u8, sql, "UNSIGNED") != null);

    // PG should NOT have UNSIGNED
    var cg_pg = Codegen.init(alloc, .pg);
    const sql_pg = try cg_pg.generateFromTypedAst(typed);
    try testing.expect(std.mem.indexOf(u8, sql_pg, "UNSIGNED") == null);
}

test "codegen: PG COMMENT ON TABLE and COLUMN" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("id", "integer");
    cols[0].comment = "primary identifier";

    const table = typed_ast_mod.TypedTable{
        .name = "items",
        .comment = "all items",
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .pg);
    const sql = try cg.generateFromTypedAst(typed);
    try testing.expect(std.mem.indexOf(u8, sql, "COMMENT ON TABLE") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "COMMENT ON COLUMN") != null);
}

test "codegen: SQLite uses -- comments" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("id", "INTEGER");
    cols[0].flags.primary_key = true;

    const table = typed_ast_mod.TypedTable{
        .name = "t",
        .comment = "test table",
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .sqlite);
    const sql = try cg.generateFromTypedAst(typed);
    try testing.expect(std.mem.indexOf(u8, sql, "-- test table") != null);
    // SQLite should not have ENGINE or CHARSET
    try testing.expect(std.mem.indexOf(u8, sql, "ENGINE") == null);
    try testing.expect(std.mem.indexOf(u8, sql, "CHARSET") == null);
}

test "codegen: multiple tables separated by blank line" {
    const alloc = testing.allocator;
    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("id", "int");
    cols[0].flags.primary_key = true;

    const t1 = typed_ast_mod.TypedTable{
        .name = "a",
        .comment = null,
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };
    const t2 = typed_ast_mod.TypedTable{
        .name = "b",
        .comment = null,
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 5,
    };

    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{ t1, t2 });
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var cg = Codegen.init(alloc, .mysql);
    const sql = try cg.generateFromTypedAst(typed);
    // Both tables should be present
    try testing.expect(std.mem.indexOf(u8, sql, "`a`") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "`b`") != null);
    // Tables should be separated
    const pos_a = std.mem.indexOf(u8, sql, "`a`").?;
    const pos_b = std.mem.indexOf(u8, sql, "`b`").?;
    try testing.expect(pos_b > pos_a);
}
