const std = @import("std");
const sem = @import("semantic.zig");
const ast_mod = @import("parser.zig");
const Field = ast_mod.Field;
const TypeInfo = ast_mod.TypeInfo;
const ModifierType = ast_mod.ModifierType;
const FkDecl = ast_mod.FkDecl;
const IndexDecl = ast_mod.IndexDecl;
const IndexType = ast_mod.IndexType;
const CheckConstraint = ast_mod.CheckConstraint;
const FkAction = ast_mod.FkAction;
const SqlComment = ast_mod.SqlComment;

pub const Codegen = struct {
    alloc: std.mem.Allocator,

    pub fn init(alloc: std.mem.Allocator) Codegen {
        return .{ .alloc = alloc };
    }

    pub fn generate(self: *Codegen, resolved: sem.ResolvedAst) ![]const u8 {
        var aw = std.Io.Writer.Allocating.init(self.alloc);
        const w = &aw.writer;

        // Header comment
        try w.writeAll("-- Generated by zig-typespec\n\n");

        // CREATE DATABASE
        if (resolved.schema_name) |name| {
            try w.print("CREATE DATABASE `{s}`;\n\n", .{name});
        }

        // CREATE TABLEs — interleaved with SQL comments by line number
        var ti: usize = 0;
        var ci: usize = 0;
        while (ti < resolved.tables.len or ci < resolved.sql_comments.len) {
            const table_line = if (ti < resolved.tables.len) resolved.tables[ti].line_no else std.math.maxInt(usize);
            const comment_line = if (ci < resolved.sql_comments.len) resolved.sql_comments[ci].line_no else std.math.maxInt(usize);

            if (comment_line < table_line) {
                // Emit SQL comment before its associated table
                try w.writeAll(resolved.sql_comments[ci].text);
                try w.writeAll("\n");
                ci += 1;
            } else if (ti < resolved.tables.len) {
                try self.generateTable(w, resolved.tables[ti]);
                ti += 1;
                if (ti < resolved.tables.len or ci < resolved.sql_comments.len) {
                    try w.writeAll("\n");
                }
            }
        }

        try w.flush();
        var out = aw.toArrayList();
        return try out.toOwnedSlice(self.alloc);
    }

    fn generateTable(self: *Codegen, w: anytype, table: sem.ResolvedTable) !void {
        _ = self;
        try w.print("CREATE TABLE `{s}` (\n", .{table.name});

        var field_count: usize = 0;

        // Fields
        for (table.fields) |field| {
            if (std.mem.eql(u8, field.name, "...")) continue;
            try w.writeAll("  ");
            try generateField(w, field);
            field_count += 1;
            try w.writeAll(",\n");
        }

        // Foreign keys
        for (table.fks) |fk| {
            try w.writeAll("  FOREIGN KEY (`");
            try w.writeAll(fk.field);
            try w.writeAll("`) REFERENCES `");
            try w.writeAll(fk.ref_table);
            try w.writeAll("`(`");
            try w.writeAll(fk.ref_field);
            try w.writeAll("`)");

            for (fk.actions) |action| {
                switch (action) {
                    .on_delete => |a| try w.print(" ON DELETE {s}", .{a}),
                    .on_update => |a| try w.print(" ON UPDATE {s}", .{a}),
                }
            }

            field_count += 1;
            try w.writeAll(",\n");
        }

        // Indexes
        for (table.indexes) |idx| {
            try w.writeAll("  ");
            switch (idx.kind) {
                .regular => try w.writeAll("INDEX"),
                .unique => try w.writeAll("UNIQUE INDEX"),
                .fulltext => try w.writeAll("FULLTEXT INDEX"),
            }
            try w.print(" `{s}` (", .{idx.name});
            for (idx.fields, 0..) |f, fi| {
                if (fi > 0) try w.writeAll(", ");
                try w.print("`{s}`", .{f});
            }
            try w.writeAll("),\n");
            field_count += 1;
        }

        // Table comment or trailing comma removal
        if (table.comment) |c| {
            const comment_text = if (c.len >= 2 and c[0] == '/' and c[1] == '/') c[2..] else c;
            const trimmed = std.mem.trim(u8, comment_text, " ");
            try w.print("  COMMENT = '{s}'\n", .{trimmed});
        } else if (field_count > 0) {
            // Remove trailing comma - back up 2 bytes (,\n) and write \n
            const pos = w.end;
            if (pos >= 2) {
                w.end = pos - 2;
                try w.writeAll("\n");
            }
        }

        try w.writeAll(");\n");
    }
};

fn generateField(w: anytype, field: Field) !void {
    try w.print("`{s}`", .{field.name});

    try w.writeAll(" ");
    switch (field.type_info) {
        .none => {
            if (std.mem.endsWith(u8, field.name, "_id")) {
                try w.writeAll("int");
            } else if (std.mem.endsWith(u8, field.name, "_on")) {
                try w.writeAll("date");
            } else if (std.mem.endsWith(u8, field.name, "_at")) {
                try w.writeAll("datetime");
            } else {
                try w.writeAll("varchar(255)");
            }
        },
        .simple => |s| {
            if (std.mem.eql(u8, s, "n")) {
                try w.writeAll("int");
            } else if (std.mem.eql(u8, s, "N")) {
                try w.writeAll("bigint");
            } else if (std.mem.eql(u8, s, "m")) {
                try w.writeAll("decimal(16, 2)");
            } else if (std.mem.eql(u8, s, "M")) {
                try w.writeAll("decimal(20, 6)");
            } else if (std.mem.eql(u8, s, "S")) {
                try w.writeAll("text");
            } else if (std.mem.eql(u8, s, "b")) {
                try w.writeAll("boolean");
            } else if (std.mem.eql(u8, s, "B")) {
                try w.writeAll("blob");
            } else if (std.mem.eql(u8, s, "j")) {
                try w.writeAll("json");
            } else if (std.mem.eql(u8, s, "d")) {
                try w.writeAll("date");
            } else if (std.mem.eql(u8, s, "t")) {
                try w.writeAll("datetime");
            } else {
                try w.writeAll(s);
            }
        },
        .int_explicit => |n| {
            try w.print("int({d})", .{n});
        },
        .decimal_explicit => |ds| {
            try w.print("decimal({d}, {d})", .{ ds.precision, ds.scale });
        },
        .varchar_explicit => |n| {
            if (n > 0) {
                try w.print("varchar({d})", .{n});
            } else {
                try w.writeAll("varchar(255)");
            }
        },
    }

    var has_auto_inc = false;
    var has_pk = false;
    var has_not_null = false;
    var is_numeric = false;
    var is_datetime = false;

    switch (field.type_info) {
        .simple => |s| {
            is_numeric = std.mem.eql(u8, s, "n") or std.mem.eql(u8, s, "N");
            is_datetime = std.mem.eql(u8, s, "t") or std.mem.eql(u8, s, "d");
        },
        .int_explicit, .decimal_explicit => is_numeric = true,
        else => {
            if (std.mem.endsWith(u8, field.name, "_id")) is_numeric = true;
            if (std.mem.endsWith(u8, field.name, "_at") or std.mem.endsWith(u8, field.name, "_on")) is_datetime = true;
        },
    }

    for (field.modifiers) |mod| {
        switch (mod.kind) {
            .auto_inc_pk => {
                if (is_numeric) {
                    has_auto_inc = true;
                    has_pk = true;
                } else if (is_datetime) {
                    try w.writeAll(" DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");
                }
            },
            .auto_inc => {
                if (is_numeric) {
                    has_auto_inc = true;
                } else if (is_datetime) {
                    try w.writeAll(" DEFAULT CURRENT_TIMESTAMP");
                }
            },
            .primary_key => has_pk = true,
            .not_null => has_not_null = true,
        }
    }

    if (field.default_val) |dv| {
        try w.print(" DEFAULT {s}", .{dv.value});
    }

    if (has_not_null) {
        try w.writeAll(" NOT NULL");
    }

    if (has_auto_inc) {
        try w.writeAll(" AUTO_INCREMENT");
    }

    if (has_pk) {
        try w.writeAll(" PRIMARY KEY");
    }

    if (field.check) |ck| {
        try w.writeAll(" CHECK (");
        try generateCheckExpr(w, field.name, ck);
        try w.writeAll(")");
    }

    if (field.comment) |c| {
        if (c.len >= 2 and c[0] == '/' and c[1] == '/') {
            try w.print(" COMMENT '{s}'", .{std.mem.trim(u8, c[2..], " ")});
        } else if (c.len >= 2 and c[0] == '-' and c[1] == '-') {
            try w.writeAll(" ");
            try w.writeAll(c);
        }
    }
}

fn generateCheckExpr(w: anytype, field_name: []const u8, ck: CheckConstraint) !void {
    switch (ck.kind) {
        .range => {
            var parts = std.mem.splitScalar(u8, ck.expr, ',');
            const low = std.mem.trim(u8, parts.next() orelse "", " ");
            const high = std.mem.trim(u8, parts.next() orelse "", " ");
            try w.print("{s} BETWEEN {s} AND {s}", .{ field_name, low, high });
        },
        .in_list => {
            try w.print("{s} IN ({s})", .{ field_name, ck.expr });
        },
        .comparison => {
            var parts = std.mem.splitScalar(u8, ck.expr, ',');
            var first = true;
            while (parts.next()) |part| {
                const trimmed = std.mem.trim(u8, part, " ");
                if (trimmed.len == 0) continue;
                if (!first) try w.writeAll(" AND ");
                first = false;

                if (trimmed[0] == '>' and trimmed.len > 1 and trimmed[1] == '=') {
                    try w.print("{s} >= {s}", .{ field_name, trimmed[2..] });
                } else if (trimmed[0] == '<' and trimmed.len > 1 and trimmed[1] == '=') {
                    try w.print("{s} <= {s}", .{ field_name, trimmed[2..] });
                } else if (trimmed[0] == '>') {
                    try w.print("{s} > {s}", .{ field_name, trimmed[1..] });
                } else if (trimmed[0] == '<') {
                    try w.print("{s} < {s}", .{ field_name, trimmed[1..] });
                } else if (trimmed[0] == '=') {
                    try w.print("{s} = {s}", .{ field_name, trimmed[1..] });
                } else {
                    try w.print("{s} = {s}", .{ field_name, trimmed });
                }
            }
        },
    }
}
