const std = @import("std");
const diff_mod = @import("diff.zig");
const sem = @import("semantic.zig");
const ast_mod = @import("ast.zig");
const codegen = @import("codegen.zig");
const typed_ast = @import("typed_ast.zig");
const dialect_mod = @import("dialect.zig");
const Field = ast_mod.Field;
const TypeInfo = ast_mod.TypeInfo;

// ─── Helpers ───────────────────────────────────────────────

fn optionalStrEq(a: ?[]const u8, b: ?[]const u8) bool {
    if (a == null and b == null) return true;
    if (a == null or b == null) return false;
    return std.mem.eql(u8, a.?, b.?);
}

pub fn generateFromDiff(
    alloc: std.mem.Allocator,
    d: diff_mod.SchemaDiff,
    old_ast: sem.ResolvedAst,
    new_ast: sem.ResolvedAst,
    dialect: codegen.Dialect,
) ![]const u8 {
    _ = old_ast;
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    try w.writeAll("-- Migration: schema diff\n");
    try w.writeAll("-- Generated by zig-typespec migrate\n\n");
    try w.writeAll("BEGIN;\n\n");

    var tr = typed_ast.TypeResolver.init(alloc);
    var cg = codegen.Codegen.init(alloc, dialect);

    // Track if anything was emitted
    var has_operations = false;

    // 1. Dropped tables
    for (d.dropped_tables) |tname| {
        has_operations = true;
        try w.writeAll("DROP TABLE IF EXISTS ");
        try dialect_mod.getBackend(dialect).quoteIdent(w, tname);
        try w.writeAll(";\n\n");
    }

    // 2. Table diffs (create or alter)
    for (d.table_diffs) |td| {
        switch (td.action) {
            .create => {
                // New table — emit CREATE TABLE using the new AST table
                has_operations = true;
                if (findResolvedTable(new_ast, td.name)) |table| {
                    var single_tables = try std.ArrayList(sem.ResolvedTable).initCapacity(alloc, 1);
                    try single_tables.append(alloc, table);
                    const single_resolved = sem.ResolvedAst{
                        .schema_name = new_ast.schema_name,
                        .schema_charset = new_ast.schema_charset,
                        .custom_types = new_ast.custom_types,
                        .tables = try single_tables.toOwnedSlice(alloc),
                        .sql_comments = &.{},
                    };
                    const single_typed = try tr.resolve(single_resolved, dialect);
                    if (single_typed.tables.len > 0) {
                        const sql = try cg.generateSingleTypedTable(single_typed.tables[0]);
                        try w.writeAll(sql);
                    }
                    try w.writeAll("\n\n");
                }
            },
            .alter => {
                // Modified table — emit ALTER statements for each diff
                var table_has_ops = false;
                var sub_needs_comma = false;

                // Field diffs
                for (td.field_diffs) |fd| {
                    switch (fd.action) {
                        .add => {
                            if (!table_has_ops) {
                                try emitAlterTable(w, dialect, td.name);
                                table_has_ops = true;
                            }
                            if (fd.new_field) |nf| {
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try w.writeAll("ADD COLUMN ");
                                const typed_col = try tr.resolveColumn(nf, dialect, new_ast.custom_types);
                                try cg.emitColumnDef(w, typed_col);
                            }
                        },
                        .drop => {
                            if (!table_has_ops) {
                                try emitAlterTable(w, dialect, td.name);
                                table_has_ops = true;
                            }
                            if (dialect == .sqlite) {
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try w.writeAll("-- WARNING: DROP COLUMN not supported in SQLite < 3.35; requires table recreation\n");
                            } else {
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try w.writeAll("DROP COLUMN ");
                                try dialect_mod.getBackend(dialect).quoteIdent(w, fd.name);
                            }
                        },
                        .modify => {
                            if (!table_has_ops) {
                                try emitAlterTable(w, dialect, td.name);
                                table_has_ops = true;
                            }
                            if (dialect == .sqlite) {
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try w.writeAll("-- WARNING: MODIFY COLUMN not supported in SQLite; requires table recreation\n");
                            } else if (fd.new_field) |nf| {
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try w.writeAll("MODIFY COLUMN ");
                                const typed_col = try tr.resolveColumn(nf, dialect, new_ast.custom_types);
                                try cg.emitColumnDef(w, typed_col);
                            }
                        },
                        .rename => {
                            if (!table_has_ops) {
                                try emitAlterTable(w, dialect, td.name);
                                table_has_ops = true;
                            }
                            if (fd.rename_from) |old_name| {
                                switch (dialect) {
                                    .mysql => {
                                        if (sub_needs_comma) try w.writeAll(",\n");
                                        sub_needs_comma = true;
                                        try w.writeAll("CHANGE COLUMN ");
                                        try dialect_mod.getBackend(dialect).quoteIdent(w, old_name);
                                        try w.writeAll(" ");
                                        if (fd.new_field) |nf| {
                                            const typed_col = try tr.resolveColumn(nf, dialect, new_ast.custom_types);
                                            try cg.emitColumnDef(w, typed_col);
                                        }
                                    },
                                    .pg, .sqlite => {
                                        if (sub_needs_comma) try w.writeAll(",\n");
                                        sub_needs_comma = true;
                                        try w.writeAll("RENAME COLUMN ");
                                        try dialect_mod.getBackend(dialect).quoteIdent(w, old_name);
                                        try w.writeAll(" TO ");
                                        try dialect_mod.getBackend(dialect).quoteIdent(w, fd.name);
                                    },
                                }
                            }
                        },
                    }
                }

                // Index diffs
                for (td.index_diffs) |idx_diff| {
                    switch (idx_diff.action) {
                        .add => {
                            if (idx_diff.new_idx) |idx| {
                                if (!table_has_ops) {
                                    try emitAlterTable(w, dialect, td.name);
                                    table_has_ops = true;
                                }
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try emitAddIndex(w, dialect, td.name, idx);
                            }
                        },
                        .drop => {
                            if (idx_diff.old_idx) |idx| {
                                if (!table_has_ops) {
                                    try emitAlterTable(w, dialect, td.name);
                                    table_has_ops = true;
                                }
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try emitDropIndex(w, dialect, td.name, idx);
                            }
                        },
                        .modify => {
                            // Drop old + add new
                            if (idx_diff.old_idx) |old_idx| {
                                if (!table_has_ops) {
                                    try emitAlterTable(w, dialect, td.name);
                                    table_has_ops = true;
                                }
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try emitDropIndex(w, dialect, td.name, old_idx);
                            }
                            if (idx_diff.new_idx) |new_idx| {
                                if (!table_has_ops) {
                                    try emitAlterTable(w, dialect, td.name);
                                    table_has_ops = true;
                                }
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try emitAddIndex(w, dialect, td.name, new_idx);
                            }
                        },
                    }
                }

                // Metadata diffs (comment, engine)
                if (td.metadata_diff) |md| {
                    // Comment change
                    if (!optionalStrEq(md.old_comment, md.new_comment)) {
                        switch (dialect) {
                            .mysql => {
                                // MySQL: ALTER TABLE ... COMMENT='new comment'
                                if (!table_has_ops) {
                                    try emitAlterTable(w, dialect, td.name);
                                    table_has_ops = true;
                                }
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                if (md.new_comment) |nc| {
                                    try w.print("COMMENT='{s}'", .{nc});
                                } else {
                                    try w.writeAll("COMMENT=''");
                                }
                            },
                            .pg => {
                                // PostgreSQL: standalone COMMENT ON TABLE
                                if (table_has_ops) {
                                    try w.writeAll(";\n\n");
                                    table_has_ops = false;
                                    sub_needs_comma = false;
                                }
                                if (md.new_comment) |nc| {
                                    try w.writeAll("COMMENT ON TABLE ");
                                    try dialect_mod.getBackend(dialect).quoteIdent(w, td.name);
                                    try w.print(" IS '{s}';\n\n", .{nc});
                                    has_operations = true;
                                }
                            },
                            .sqlite => {
                                // SQLite: comments are not supported in ALTER TABLE
                                if (!table_has_ops) {
                                    try emitAlterTable(w, dialect, td.name);
                                    table_has_ops = true;
                                }
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try w.print("-- NOTE: Comment change not supported via ALTER TABLE in SQLite\n", .{});
                            },
                        }
                    }
                    // Engine change (MySQL only)
                    if (!optionalStrEq(md.old_engine, md.new_engine)) {
                        if (dialect == .mysql) {
                            if (!table_has_ops) {
                                try emitAlterTable(w, dialect, td.name);
                                table_has_ops = true;
                            }
                            if (sub_needs_comma) try w.writeAll(",\n");
                            sub_needs_comma = true;
                            const eng = md.new_engine orelse "InnoDB";
                            try w.print("ENGINE={s}", .{eng});
                        }
                        // PG/SQLite: engine is not applicable
                    }
                }

                // FK diffs
                for (td.fk_diffs) |fk_diff| {
                    switch (fk_diff.action) {
                        .add => {
                            if (fk_diff.new_fk) |fk| {
                                if (!table_has_ops) {
                                    try emitAlterTable(w, dialect, td.name);
                                    table_has_ops = true;
                                }
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try emitAddFk(w, dialect, td.name, fk);
                            }
                        },
                        .drop => {
                            if (fk_diff.old_fk) |fk| {
                                if (!table_has_ops) {
                                    try emitAlterTable(w, dialect, td.name);
                                    table_has_ops = true;
                                }
                                if (sub_needs_comma) try w.writeAll(",\n");
                                sub_needs_comma = true;
                                try emitDropFk(w, dialect, td.name, fk);
                            }
                        },
                    }
                }

                if (table_has_ops) {
                    has_operations = true;
                    try w.writeAll(";\n");
                }
            },
        }
    }

    try w.writeAll("COMMIT;\n");

    try w.flush();
    var out = aw.toArrayList();
    return try out.toOwnedSlice(alloc);
}

fn emitAlterTable(w: anytype, dialect: codegen.Dialect, table_name: []const u8) !void {
    try w.writeAll("ALTER TABLE ");
    try dialect_mod.getBackend(dialect).quoteIdent(w, table_name);
    try w.writeAll("\n");
}

fn emitAddIndex(w: anytype, dialect: codegen.Dialect, table_name: []const u8, idx: ast_mod.IndexDecl) !void {
    switch (dialect) {
        .mysql => {
            switch (idx.kind) {
                .regular => {
                    try w.print("ADD INDEX `{s}` (", .{idx.name});
                    try emitIndexFields(w, .mysql, idx);
                    try w.writeAll(")");
                },
                .unique => {
                    try w.print("ADD UNIQUE INDEX `{s}` (", .{idx.name});
                    try emitIndexFields(w, .mysql, idx);
                    try w.writeAll(")");
                },
                .fulltext => {
                    try w.print("ADD FULLTEXT INDEX `{s}` (", .{idx.name});
                    try emitIndexFields(w, .mysql, idx);
                    try w.writeAll(")");
                },
                .primary_key => {
                    try w.writeAll("ADD PRIMARY KEY (");
                    try emitIndexFields(w, .mysql, idx);
                    try w.writeAll(")");
                },
            }
        },
        .pg => {
            switch (idx.kind) {
                .unique => {
                    try w.writeAll("ADD UNIQUE (");
                    try emitIndexFields(w, .pg, idx);
                    try w.writeAll(")");
                },
                .primary_key => {
                    try w.writeAll("ADD PRIMARY KEY (");
                    try emitIndexFields(w, .pg, idx);
                    try w.writeAll(")");
                },
                else => {
                    // PG: regular/fulltext indexes can't be added via ALTER TABLE
                    // Emit as comment
                    try w.print("-- NOTE: CREATE INDEX needed for '{s}' (not supported via ALTER TABLE in PG)\n", .{idx.name});
                },
            }
        },
        .sqlite => {
            // SQLite: can't add indexes via ALTER TABLE; emit CREATE INDEX as standalone
            switch (idx.kind) {
                .unique => {
                    try w.print("CREATE UNIQUE INDEX IF NOT EXISTS \"uk_{s}\" ON ", .{idx.name});
                    try dialect_mod.getBackend(.sqlite).quoteIdent(w, table_name);
                    try w.writeAll(" (");
                    try emitIndexFields(w, .sqlite, idx);
                    try w.writeAll(")");
                },
                .regular => {
                    try w.print("CREATE INDEX IF NOT EXISTS \"idx_{s}\" ON ", .{idx.name});
                    try dialect_mod.getBackend(.sqlite).quoteIdent(w, table_name);
                    try w.writeAll(" (");
                    try emitIndexFields(w, .sqlite, idx);
                    try w.writeAll(")");
                },
                else => {
                    try w.print("-- NOTE: PRIMARY KEY/FULLTEXT cannot be added via ALTER TABLE in SQLite\n", .{});
                },
            }
        },
    }
}

fn emitDropIndex(w: anytype, dialect: codegen.Dialect, table_name: []const u8, idx: ast_mod.IndexDecl) !void {
    _ = table_name;
    switch (dialect) {
        .mysql => {
            switch (idx.kind) {
                .primary_key => try w.writeAll("DROP PRIMARY KEY"),
                else => try w.print("DROP INDEX `{s}`", .{idx.name}),
            }
        },
        .pg, .sqlite => {
            switch (idx.kind) {
                .primary_key => try w.writeAll("DROP PRIMARY KEY"),
                else => try w.print("DROP INDEX IF EXISTS \"{s}\"", .{idx.name}),
            }
        },
    }
}

fn emitIndexFields(w: anytype, dialect: codegen.Dialect, idx: ast_mod.IndexDecl) !void {
    for (idx.fields, 0..) |f, fi| {
        if (fi > 0) try w.writeAll(", ");
        switch (dialect) {
            .mysql => try w.print("`{s}`", .{f}),
            .pg, .sqlite => try w.print("\"{s}\"", .{f}),
        }
    }
}

fn emitAddFk(w: anytype, dialect: codegen.Dialect, table_name: []const u8, fk: ast_mod.FkDecl) !void {
    _ = table_name;
    try w.writeAll("ADD FOREIGN KEY (");
    for (fk.fields, 0..) |f, fi| {
        if (fi > 0) try w.writeAll(", ");
        try dialect_mod.getBackend(dialect).quoteIdent(w, f);
    }
    try w.writeAll(") REFERENCES ");
    try dialect_mod.getBackend(dialect).quoteIdent(w, fk.ref_table);
    try w.writeAll("(");
    for (fk.ref_fields, 0..) |f, fi| {
        if (fi > 0) try w.writeAll(", ");
        try dialect_mod.getBackend(dialect).quoteIdent(w, f);
    }
    try w.writeAll(")");
    for (fk.actions) |action| {
        try w.writeAll(" ");
        switch (action.trigger) {
            .on_delete => try w.writeAll("ON DELETE"),
            .on_update => try w.writeAll("ON UPDATE"),
        }
        try w.writeAll(" ");
        switch (action.action) {
            .cascade => try w.writeAll("CASCADE"),
            .set_null => try w.writeAll("SET NULL"),
        }
    }
}

fn emitDropFk(w: anytype, dialect: codegen.Dialect, table_name: []const u8, fk: ast_mod.FkDecl) !void {
    _ = table_name;
    if (dialect == .sqlite) {
        try w.writeAll("-- WARNING: DROP FOREIGN KEY not supported via ALTER TABLE in SQLite\n");
        return;
    }
    // Generate a FK constraint name from the local fields
    try w.writeAll("DROP FOREIGN KEY ");
    switch (dialect) {
        .mysql => {
            try w.writeAll("fk_");
            for (fk.fields) |f| {
                try w.writeAll(f);
            }
        },
        .pg => {
            try w.writeAll("\"fk_");
            for (fk.fields) |f| {
                try w.writeAll(f);
            }
            try w.writeAll("\"");
        },
        .sqlite => unreachable, // handled above
    }
}

fn findResolvedTable(ast: sem.ResolvedAst, name: []const u8) ?sem.ResolvedTable {
    for (ast.tables) |table| {
        if (std.mem.eql(u8, table.name, name)) return table;
    }
    return null;
}

// ─── Unit Tests ─────────────────────────────────────────────

const testing = std.testing;

fn emptyResolvedAst() sem.ResolvedAst {
    return .{
        .schema_name = null,
        .schema_charset = null,
        .custom_types = &.{},
        .tables = &.{},
        .sql_comments = &.{},
    };
}

test "migrate: empty diff produces BEGIN/COMMIT wrapper" {
    const alloc = testing.allocator;
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyResolvedAst(), emptyResolvedAst(), .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "BEGIN;") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "COMMIT;") != null);
}

test "migrate: dropped table generates DROP TABLE" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{"users"});
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
    };
    const sql = try generateFromDiff(alloc, d, emptyResolvedAst(), emptyResolvedAst(), .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "DROP TABLE IF EXISTS") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "users") != null);
}

test "migrate: dropped table with PG dialect uses double quotes" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{"accounts"});
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
    };
    const sql = try generateFromDiff(alloc, d, emptyResolvedAst(), emptyResolvedAst(), .pg);
    try testing.expect(std.mem.indexOf(u8, sql, "\"accounts\"") != null);
}

test "migrate: dropped table with SQLite dialect uses double quotes" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{"logs"});
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
    };
    const sql = try generateFromDiff(alloc, d, emptyResolvedAst(), emptyResolvedAst(), .sqlite);
    try testing.expect(std.mem.indexOf(u8, sql, "\"logs\"") != null);
}

test "migrate: migration header present" {
    const alloc = testing.allocator;
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyResolvedAst(), emptyResolvedAst(), .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "-- Migration: schema diff") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "-- Generated by zig-typespec migrate") != null);
}

test "migrate: multiple dropped tables" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{ "users", "orders", "products" });
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
    };
    const sql = try generateFromDiff(alloc, d, emptyResolvedAst(), emptyResolvedAst(), .mysql);
    // Count DROP TABLE statements
    var count: usize = 0;
    var search_sql = sql;
    while (std.mem.indexOf(u8, search_sql, "DROP TABLE")) |pos| {
        count += 1;
        search_sql = search_sql[pos + 1 ..];
    }
    try testing.expectEqual(@as(usize, 3), count);
}
