const std = @import("std");
const diff_mod = @import("diff.zig");
const ast_mod = @import("ast.zig");
const codegen = @import("codegen.zig");
const typed_ast = @import("typed_ast.zig");
const dialect_mod = @import("dialect.zig");
const dialect_enum = @import("dialect_enum.zig");
const utils = @import("utils.zig");
const Field = ast_mod.Field;
const TypeInfo = ast_mod.TypeInfo;

const Dialect = dialect_enum.Dialect;

// ─── Helpers ───────────────────────────────────────────────

const optionalStrEq = utils.optionalStrEq;

fn emitComma(w: anytype, needs_comma: *bool) !void {
    if (needs_comma.*) try w.writeAll(",\n");
    needs_comma.* = true;
}

fn beginAlterTable(w: anytype, backend: dialect_mod.DialectBackend, table_name: []const u8, table_has_ops: *bool) !void {
    if (!table_has_ops.*) {
        try w.writeAll("ALTER TABLE ");
        try backend.quoteIdent(w, table_name);
        try w.writeAll("\n");
        table_has_ops.* = true;
    }
}

pub fn generateFromDiff(
    alloc: std.mem.Allocator,
    d: diff_mod.SchemaDiff,
    new_typed: typed_ast.TypedAst,
    new_resolved: ast_mod.ResolvedAst,
    dialect: Dialect,
) ![]const u8 {
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    try w.writeAll("-- Migration: schema diff\n");
    try w.writeAll("-- Generated by zig-typespec migrate\n\n");
    try w.writeAll("BEGIN;\n\n");

    var tr = typed_ast.TypeResolver.init(alloc);
    var cg = codegen.Codegen.init(alloc, dialect);
    const backend = dialect_mod.getBackend(dialect);

    // Track if anything was emitted
    var has_operations = false;

    // 1. Dropped tables
    for (d.dropped_tables) |tname| {
        has_operations = true;
        try w.writeAll("DROP TABLE IF EXISTS ");
        try backend.quoteIdent(w, tname);
        try w.writeAll(";\n\n");
    }

    // 2. View diffs (create, drop, modify)
    for (d.view_diffs) |vd| {
        has_operations = true;
        switch (vd.action) {
            .drop => {
                try w.writeAll("DROP VIEW IF EXISTS ");
                try backend.quoteIdent(w, vd.name);
                try w.writeAll(";\n\n");
            },
            .create, .modify => {
                // For modify: drop then recreate (no ALTER VIEW in most dialects)
                if (vd.action == .modify) {
                    try w.writeAll("DROP VIEW IF EXISTS ");
                    try backend.quoteIdent(w, vd.name);
                    try w.writeAll(";\n\n");
                }
                // Find the view query from the new typed AST
                if (findTypedView(new_typed, vd.name)) |view| {
                    try backend.emitCreateView(w, view.name, view.query);
                    try w.writeAll("\n");
                }
            },
        }
    }

    // 2. Table diffs (create or alter)
    for (d.table_diffs) |td| {
        switch (td.action) {
            .create => {
                // New table — emit CREATE TABLE using the new AST table
                has_operations = true;
                if (findResolvedTable(new_resolved, td.name)) |table| {
                    var single_tables = try std.ArrayList(ast_mod.ResolvedTable).initCapacity(alloc, 1);
                    try single_tables.append(alloc, table);
                    const single_resolved = ast_mod.ResolvedAst{
                        .schema_name = new_resolved.schema_name,
                        .schema_charset = new_resolved.schema_charset,
                        .custom_types = new_resolved.custom_types,
                        .tables = try single_tables.toOwnedSlice(alloc),
                        .views = &.{},
                        .sql_comments = &.{},
                    };
                    const single_typed = try tr.resolve(single_resolved, dialect);
                    if (single_typed.tables.len > 0) {
                        try cg.generateTypedTable(w, single_typed.tables[0]);
                    }
                    try w.writeAll("\n\n");
                }
            },
            .alter => {
                // Modified table — emit ALTER statements for each diff
                var table_has_ops = false;
                var sub_needs_comma = false;

                // Field diffs
                for (td.field_diffs) |fd| {
                    switch (fd.action) {
                        .add => {
                            try beginAlterTable(w, backend, td.name, &table_has_ops);
                            if (fd.new_field) |nf| {
                                try emitComma(w, &sub_needs_comma);
                                try w.writeAll("ADD COLUMN ");
                                const typed_col = try tr.resolveColumn(nf, dialect, new_resolved.custom_types);
                                try cg.emitColumnDef(w, typed_col);
                            }
                        },
                        .drop => {
                            try beginAlterTable(w, backend, td.name, &table_has_ops);
                            try emitComma(w, &sub_needs_comma);
                            try backend.emitAlterDropColumn(w, fd.name);
                        },
                        .modify => {
                            try beginAlterTable(w, backend, td.name, &table_has_ops);
                            if (fd.new_field) |nf| {
                                try emitComma(w, &sub_needs_comma);
                                try backend.emitAlterModifyColumn(w, nf.name);
                                if (backend.modify_needs_column_def) {
                                    const typed_col = try tr.resolveColumn(nf, dialect, new_resolved.custom_types);
                                    try cg.emitColumnDefEx(w, typed_col, backend.modify_column_def_skips_name);
                                }
                            }
                        },
                        .rename => {
                            try beginAlterTable(w, backend, td.name, &table_has_ops);
                            if (fd.rename_from) |old_name| {
                                try emitComma(w, &sub_needs_comma);
                                try backend.emitAlterRenameColumn(w, old_name, fd.name);
                                if (backend.rename_needs_column_def) {
                                    if (fd.new_field) |nf| {
                                        const typed_col = try tr.resolveColumn(nf, dialect, new_resolved.custom_types);
                                        try cg.emitColumnDef(w, typed_col);
                                    }
                                }
                            }
                        },
                    }
                }

                // Index diffs
                for (td.index_diffs) |idx_diff| {
                    switch (idx_diff.action) {
                        .add => {
                            if (idx_diff.new_idx) |idx| {
                                try beginAlterTable(w, backend, td.name, &table_has_ops);
                                try emitComma(w, &sub_needs_comma);
                                try backend.emitAlterAddIndex(w, td.name, idx);
                            }
                        },
                        .drop => {
                            if (idx_diff.old_idx) |idx| {
                                try beginAlterTable(w, backend, td.name, &table_has_ops);
                                try emitComma(w, &sub_needs_comma);
                                try backend.emitAlterDropIndex(w, idx);
                            }
                        },
                        .modify => {
                            // Drop old + add new
                            if (idx_diff.old_idx) |old_idx| {
                                try beginAlterTable(w, backend, td.name, &table_has_ops);
                                try emitComma(w, &sub_needs_comma);
                                try backend.emitAlterDropIndex(w, old_idx);
                            }
                            if (idx_diff.new_idx) |new_idx| {
                                try beginAlterTable(w, backend, td.name, &table_has_ops);
                                try emitComma(w, &sub_needs_comma);
                                try backend.emitAlterAddIndex(w, td.name, new_idx);
                            }
                        },
                    }
                }

                // Metadata diffs (comment, engine)
                if (td.metadata_diff) |md| {
                    // Comment change — two-phase: check result type, then set up state, then emit
                    if (!optionalStrEq(md.old_comment, md.new_comment)) {
                        if (md.new_comment) |nc| {
                            const result = backend.commentResult();
                            switch (result) {
                                .added_to_alter => {
                                    // MySQL: comment is inline in ALTER TABLE
                                    try beginAlterTable(w, backend, td.name, &table_has_ops);
                                    try emitComma(w, &sub_needs_comma);
                                    try backend.emitAlterTableComment(w, td.name, nc);
                                },
                                .standalone_emitted => {
                                    // PG: standalone COMMENT ON TABLE — close current ALTER TABLE if open
                                    if (table_has_ops) {
                                        try w.writeAll(";\n\n");
                                        table_has_ops = false;
                                        sub_needs_comma = false;
                                    }
                                    try backend.emitAlterTableComment(w, td.name, nc);
                                    has_operations = true;
                                },
                                .unsupported => {
                                    // SQLite: warning comment — add to ALTER TABLE
                                    try beginAlterTable(w, backend, td.name, &table_has_ops);
                                    try emitComma(w, &sub_needs_comma);
                                    try backend.emitAlterTableComment(w, td.name, nc);
                                },
                            }
                        }
                    }
                    // Engine change
                    if (!optionalStrEq(md.old_engine, md.new_engine)) {
                        try beginAlterTable(w, backend, td.name, &table_has_ops);
                        try emitComma(w, &sub_needs_comma);
                        try backend.emitAlterEngine(w, md.new_engine);
                    }
                }

                // FK diffs
                for (td.fk_diffs) |fk_diff| {
                    switch (fk_diff.action) {
                        .add => {
                            if (fk_diff.new_fk) |fk| {
                                try beginAlterTable(w, backend, td.name, &table_has_ops);
                                try emitComma(w, &sub_needs_comma);
                                try w.writeAll("ADD FOREIGN KEY (");
                                for (fk.fields, 0..) |f, fi| {
                                    if (fi > 0) try w.writeAll(", ");
                                    try backend.quoteIdent(w, f);
                                }
                                try w.writeAll(") REFERENCES ");
                                try backend.quoteIdent(w, fk.ref_table);
                                try w.writeAll("(");
                                for (fk.ref_fields, 0..) |f, fi| {
                                    if (fi > 0) try w.writeAll(", ");
                                    try backend.quoteIdent(w, f);
                                }
                                try w.writeAll(")");
                                for (fk.actions) |action| {
                                    try w.writeAll(" ");
                                    switch (action.trigger) {
                                        .on_delete => try w.writeAll("ON DELETE"),
                                        .on_update => try w.writeAll("ON UPDATE"),
                                    }
                                    try w.writeAll(" ");
                                    switch (action.action) {
                                        .cascade => try w.writeAll("CASCADE"),
                                        .set_null => try w.writeAll("SET NULL"),
                                    }
                                }
                            }
                        },
                        .drop => {
                            if (fk_diff.old_fk) |fk| {
                                try beginAlterTable(w, backend, td.name, &table_has_ops);
                                try emitComma(w, &sub_needs_comma);
                                try backend.emitAlterDropFk(w, fk);
                            }
                        },
                    }
                }

                if (table_has_ops) {
                    has_operations = true;
                    try w.writeAll(";\n");
                }
            },
        }
    }

    try w.writeAll("COMMIT;\n");

    try w.flush();
    var out = aw.toArrayList();
    return try out.toOwnedSlice(alloc);
}

fn findResolvedTable(ast: ast_mod.ResolvedAst, name: []const u8) ?ast_mod.ResolvedTable {
    for (ast.tables) |table| {
        if (std.mem.eql(u8, table.name, name)) return table;
    }
    return null;
}

fn findTypedView(typed: typed_ast.TypedAst, name: []const u8) ?typed_ast.TypedView {
    for (typed.views) |view| {
        if (std.mem.eql(u8, view.name, name)) return view;
    }
    return null;
}

// ─── Unit Tests ─────────────────────────────────────────────

const testing = std.testing;

fn emptyResolvedAst() ast_mod.ResolvedAst {
    return .{
        .schema_name = null,
        .schema_charset = null,
        .custom_types = &.{},
        .tables = &.{},
        .views = &.{},
        .sql_comments = &.{},
    };
}

fn emptyTypedAst() typed_ast.TypedAst {
    return .{
        .schema_name = null,
        .schema_charset = null,
        .tables = &.{},
        .views = &.{},
        .sql_comments = &.{},
    };
}

test "migrate: empty diff produces BEGIN/COMMIT wrapper" {
    const alloc = testing.allocator;
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = &.{},
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "BEGIN;") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "COMMIT;") != null);
}

test "migrate: dropped table generates DROP TABLE" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{"users"});
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "DROP TABLE IF EXISTS") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "users") != null);
}

test "migrate: dropped table with PG dialect uses double quotes" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{"accounts"});
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .pg);
    try testing.expect(std.mem.indexOf(u8, sql, "\"accounts\"") != null);
}

test "migrate: dropped table with SQLite dialect uses double quotes" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{"logs"});
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .sqlite);
    try testing.expect(std.mem.indexOf(u8, sql, "\"logs\"") != null);
}

test "migrate: migration header present" {
    const alloc = testing.allocator;
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "-- Migration: schema diff") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "-- Generated by zig-typespec migrate") != null);
}

test "migrate: multiple dropped tables" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{ "users", "orders", "products" });
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .mysql);
    // Count DROP TABLE statements
    var count: usize = 0;
    var search_sql = sql;
    while (std.mem.indexOf(u8, search_sql, "DROP TABLE")) |pos| {
        count += 1;
        search_sql = search_sql[pos + 1 ..];
    }
    try testing.expectEqual(@as(usize, 3), count);
}
