const std = @import("std");
const migrate_mod = @import("../diff/migrate.zig");
const diff_mod = @import("../diff/engine.zig");
const ast_mod = @import("../types/ast.zig");
const typed_ast = @import("../types/typed_ast.zig");
const generateFromDiff = migrate_mod.generateFromDiff;

const testing = std.testing;

fn emptyResolvedAst() ast_mod.ResolvedAst {
    return .{
        .schema_name = null,
        .schema_charset = null,
        .custom_types = &.{},
        .tables = &.{},
        .views = &.{},
        .sql_comments = &.{},
    };
}

fn emptyTypedAst() typed_ast.TypedAst {
    return .{
        .schema_name = null,
        .schema_charset = null,
        .tables = &.{},
        .views = &.{},
        .sql_comments = &.{},
    };
}

test "migrate: empty diff produces BEGIN/COMMIT wrapper" {
    const alloc = testing.allocator;
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = &.{},
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "BEGIN;") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "COMMIT;") != null);
}

test "migrate: dropped table generates DROP TABLE" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{"users"});
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "DROP TABLE IF EXISTS") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "users") != null);
}

test "migrate: dropped table with PG dialect uses double quotes" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{"accounts"});
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .pg);
    try testing.expect(std.mem.indexOf(u8, sql, "\"accounts\"") != null);
}

test "migrate: dropped table with SQLite dialect uses double quotes" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{"logs"});
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .sqlite);
    try testing.expect(std.mem.indexOf(u8, sql, "\"logs\"") != null);
}

test "migrate: migration header present" {
    const alloc = testing.allocator;
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "-- Migration: schema diff") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "-- Generated by rune migrate") != null);
}

test "migrate: multiple dropped tables" {
    const alloc = testing.allocator;
    const dropped = try alloc.dupe([]const u8, &.{ "users", "orders", "products" });
    const d = diff_mod.SchemaDiff{
        .table_diffs = &.{},
        .dropped_tables = dropped,
        .view_diffs = &.{},
    };
    const sql = try generateFromDiff(alloc, d, emptyTypedAst(), emptyResolvedAst(), .mysql);
    var count: usize = 0;
    var search_sql = sql;
    while (std.mem.indexOf(u8, search_sql, "DROP TABLE")) |pos| {
        count += 1;
        search_sql = search_sql[pos + 1 ..];
    }
    try testing.expectEqual(@as(usize, 3), count);
}
