warning: modifier invalid for this type — expected n, N, integer types, t, d for this modifier, got 'id'
  --> input.tps:2:1
   |
 2 | id bigint ++ : 测试列
    ^^
warning: 'auto_increment' modifier has no effect on non-numeric/non-datetime type in field 'id'
  --> input.tps:2
-- Generated by zig-typespec

CREATE TABLE ``test_table`` (
  `id` bigint AUTO_INCREMENT PRIMARY KEY COMMENT '测试列'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='测试表';
