-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "all_types" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "full" text,
  "price" numeric(16, 2),
  "big_p" numeric(20, 6),
  "flag" boolean,
  "data" bytea,
  "meta" json,
  "created" timestamp,
  "born" date,
  "code" varchar(64),
  "ver" bigint,
  "amt" numeric(10, 2),
  "cnt" integer
);
