-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `all_types` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255),
  `full` text,
  `price` decimal(16, 2),
  `big_p` decimal(20, 6),
  `flag` boolean,
  `data` blob,
  `meta` json,
  `created` datetime,
  `born` date,
  `code` varchar(64),
  `ver` bigint,
  `amt` decimal(10, 2),
  `cnt` int(128)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
