-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "modifiers" (
  "col1" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "col2" integer GENERATED ALWAYS AS IDENTITY,
  "col3" integer PRIMARY KEY,
  "col4" integer NOT NULL,
  "col5" integer DEFAULT 0,
  "col6" integer NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "col7" integer NOT NULL PRIMARY KEY,
  "col8" timestamp DEFAULT CURRENT_TIMESTAMP,
  "col9" timestamp DEFAULT CURRENT_TIMESTAMP
);
