-- Generated by rune

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `defaults` (
  `col1` int DEFAULT 0,
  `col2` varchar(255) DEFAULT 'hello',
  `col3` decimal(16, 2) DEFAULT 0,
  `col4` varchar(255) DEFAULT 0,
  `col5` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
