-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `suffixes` (
  `user_id` int,
  `order_id` int,
  `created_at` datetime,
  `updated_at` datetime,
  `paid_on` date,
  `deleted_on` date,
  `name` TEXT,
  `content` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
