-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "suffixes" (
  "user_id" integer,
  "order_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "paid_on" date,
  "deleted_on" date,
  "name" varchar(255),
  "content" varchar(255)
);
