-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

-- This is a SQL comment (passed through)
CREATE TABLE "comments" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32) NOT NULL,
  "email" varchar(128) NOT NULL,
  "bio" text
);
COMMENT ON COLUMN "comments"."name" IS '用户名';
COMMENT ON COLUMN "comments"."email" IS '邮箱地址';
COMMENT ON COLUMN "comments"."bio" IS '个人简介';
