-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

-- This is a SQL comment (passed through)
CREATE TABLE `comments` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(32) NOT NULL COMMENT '用户名',
  `email` varchar(128) NOT NULL COMMENT '邮箱地址',
  `bio` text COMMENT '个人简介'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
