-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `unsigned_test` (
  `plain_n` int,
  `plain_N` bigint,
  `plus_n` int UNSIGNED,
  `plus_N` bigint UNSIGNED,
  `plus_n_pk` int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `plus_N_nn` bigint UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
