-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "unsigned_test" (
  "plain_n" integer,
  "plain_N" bigint,
  "plus_n" integer,
  "plus_N" bigint,
  "plus_n_pk" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "plus_N_nn" bigint NOT NULL
);
