-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "item" (
  "name" varchar(64) NOT NULL,
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "status" integer DEFAULT 0,
  "version" bigint
);
