-- Generated by rune

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `parent` (
  `id` int AUTO_INCREMENT PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `child` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `parent_id` int,
  FOREIGN KEY (`parent_id`) REFERENCES `parent`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
