-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "indexed" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32),
  "email" varchar(128),
  "content" text,
  UNIQUE ("email"),
  ("name"),
  -- WARNING: FULLTEXT INDEX not supported inline in PostgreSQL, skipping
  
);
