-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `indexed` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(32),
  `email` varchar(128),
  `content` text,
  UNIQUE INDEX `uk_email` (`email`),
  INDEX `idx_name` (`name`),
  FULLTEXT INDEX `ft_content` (`content`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
