-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "multi" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32),
  "email" varchar(128),
  "status" integer,
  UNIQUE ("email", "status")
);
CREATE INDEX "idx_name_email" ON "multi" ("name", "email");
