-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `multi` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(32),
  `email` varchar(128),
  `status` int(1),
  INDEX `idx_name_email` (`name`, `email`),
  UNIQUE INDEX `uk_email_status` (`email`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
