-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "constrained" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "age" integer CHECK (age BETWEEN 0 AND 150),
  "score" numeric(16, 2) CHECK (score BETWEEN 0 AND 100),
  "amount" numeric(16, 2) CHECK (amount > 0),
  "qty" integer CHECK (qty >= 1),
  "type" varchar(16) CHECK (type IN ('a', 'b', 'c')),
  "range2" integer CHECK (range2 >= 0 AND range2 <= 100)
);
