-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `constrained` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `age` int CHECK (age BETWEEN 0 AND 150),
  `score` decimal(16, 2) CHECK (score BETWEEN 0 AND 100),
  `amount` decimal(16, 2) CHECK (amount > 0),
  `qty` int CHECK (qty >= 1),
  `type` varchar(16) CHECK (type IN ('a', 'b', 'c')),
  `range2` int CHECK (range2 >= 0 AND range2 <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
