-- Generated by rune

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(32) NOT NULL,
  `email` varchar(256) NOT NULL,
  `phone` varchar(16)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
