-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "version" bigint,
  "name" varchar(32) NOT NULL,
  "email" varchar(128) NOT NULL
);

CREATE TABLE "product" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "version" bigint,
  "name" varchar(128) NOT NULL,
  "price" numeric(16, 2)
);
