-- Generated by rune

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `user` (
  `email` varchar(128) NOT NULL,
  `phone` varchar(16),
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
