-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "idx_test" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32),
  "email" varchar(128),
  "content" text,
  UNIQUE ("email")
);
CREATE INDEX "idx_name" ON "idx_test" ("name");
