-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "compound_check" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "balance" numeric(16, 2) CHECK (balance >= 0 AND balance <= 99999),
  "score" integer CHECK (score > 0 AND score <= 100)
);
