-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `bare_fields` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` int,
  `order_id` int,
  `name` varchar(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
