-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "version" bigint,
  "status" integer DEFAULT 0,
  "name" varchar(32) NOT NULL,
  "email" varchar(128) NOT NULL
);
