-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "sql_comment_field" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32),
  "email" varchar(128)
);
