-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `sql_comment_field` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(32),
  `email` varchar(128)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
