-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "defaults_many" (
  "col_int" integer DEFAULT 42,
  "col_str" varchar(255) DEFAULT 'hello',
  "col_zero" integer DEFAULT 0,
  "col_one" integer DEFAULT 1,
  "col_empty" varchar(255) DEFAULT 0,
  "col_big" bigint DEFAULT 999999999,
  "col_m" numeric(16, 2) DEFAULT 0
);
