-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "standalone_mod" (
  "col1" integer NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "col2" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "col3" varchar(255) NOT NULL,
  "col4" timestamp DEFAULT CURRENT_TIMESTAMP
);
