-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "status_check" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "status" varchar(16) CHECK (status IN ('active', 'inactive', 'pending')),
  "priority" integer CHECK (priority IN (1, 2, 3, 4, 5))
);
