-- Generated by rune

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `status_check` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `status` varchar(16) CHECK (status IN ('active', 'inactive', 'pending')),
  `priority` int CHECK (priority IN (1, 2, 3, 4, 5))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
