-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "gender" TEXT NOT NULL CHECK ("gender" IN ('M', 'F', 'X')),
  "status" TEXT DEFAULT 'pending' CHECK ("status" IN ('pending', 'active', 'closed')),
  "role" TEXT CHECK ("role" IN ('admin', 'user', 'guest'))
);
