-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `gender` ENUM('M', 'F', 'X') NOT NULL,
  `status` ENUM('pending', 'active', 'closed') DEFAULT 'pending',
  `role` ENUM('admin', 'user', 'guest')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
