-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "gender" text NOT NULL CHECK ("gender" IN ('M', 'F', 'X')),
  "status" text DEFAULT 'pending' CHECK ("status" IN ('pending', 'active', 'closed')),
  "role" text CHECK ("role" IN ('admin', 'user', 'guest'))
);
