-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `counters` (
  `small_num` int UNSIGNED,
  `big_num` bigint UNSIGNED,
  `plain_int` int,
  `unsigned32` int UNSIGNED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
