-- Generated by rune

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `email` varchar(128) NOT NULL,
  `name` varchar(32),
  `code` varchar(16),
  UNIQUE INDEX `uk_email` (`email`),
  UNIQUE INDEX `uk_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
