-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `version` bigint,
  `deleted_at` datetime,
  `deleted_by` int,
  `name` varchar(32) NOT NULL,
  `email` varchar(128) NOT NULL,
  `phone` varchar(16)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
