-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "order" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "order_no" varchar(64) NOT NULL,
  "amount" numeric(16, 2) NOT NULL,
  FOREIGN KEY ("id") REFERENCES "user"("id")
);
