-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32),
  "email" varchar(128),
  "status" integer DEFAULT 0,
  "create_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  ,
  UNIQUE ("email", "status")
);
