-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32),
  "email" varchar(128) NOT NULL,
  "phone" varchar(16),
  (name),
  UNIQUE (email)
);
