-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32)
);

CREATE TABLE "order" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "order_no" varchar(64) NOT NULL,
  "user_id" integer,
  "amount" numeric(16, 2) NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "payment" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "amount" numeric(16, 2) NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
