-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32)
);

CREATE TABLE "t1" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t2" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t3" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t4" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t5" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t6" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
