-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "users" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "role" TEXT CHECK ("role" IN ('admin', 'user', 'guest')),
  "status" TEXT CHECK ("status" IN ('A', 'B', 'C'))
);
