-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "users" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "role" text CHECK ("role" IN ('admin', 'user', 'guest')),
  "status" text CHECK ("status" IN ('A', 'B', 'C'))
);
