-- Generated by zig-typespec

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `users` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `role` ENUM('admin', 'user', 'guest'),
  `status` ENUM('A', 'B', 'C')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
