-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "constrained" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "age" integer CHECK (age BETWEEN 0 AND 150),
  "amount" numeric(16, 2) CHECK (amount > 0),
  "ratio" numeric(20, 6) CHECK (ratio >= 0 AND ratio <= 100),
  "type" varchar(16) CHECK (type IN ('a', 'b', 'c'))
);
