-- Generated by zig-typespec

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "age_upper" integer DEFAULT 0 CHECK (age_upper >= 0 AND age_upper < 150),
  "age_lower" integer DEFAULT 0 CHECK (age_lower > 0 AND age_lower <= 150),
  "age_both" integer DEFAULT 0 CHECK (age_both > 0 AND age_both < 150)
);
