-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "status" integer DEFAULT 0 CHECK (status IN (0, 1, 2)),
  "type" varchar(16) CHECK (type IN ('a', 'b', 'c')),
  "level" integer CHECK (level IN (1, 2, 3, 4, 5))
);
