-- Generated by rune

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `amount` decimal(16, 2) CHECK (amount > 0),
  `ratio` decimal(20, 6) CHECK (ratio >= 0 AND ratio <= 100),
  `score` int CHECK (score >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
