-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "amount" numeric(16, 2) CHECK (amount > 0),
  "ratio" numeric(20, 6) CHECK (ratio >= 0 AND ratio <= 100),
  "score" integer CHECK (score >= 0)
);
