-- Generated by rune

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32) NOT NULL
);

CREATE TABLE "coupon" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE "order" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "coupon_id" integer,
  "amount" numeric(16, 2),
  FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("coupon_id") REFERENCES "coupon"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
