-- Generated by rune

CREATE DATABASE `test_custom_types` CHARACTER SET utf8mb4;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `uuid` varchar(36) NOT NULL,
  `email` varchar(128) NOT NULL,
  `name` varchar(64) NOT NULL,
  `ip` varchar(45)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
