-- Migration: schema diff
-- Generated by rune migrate

BEGIN;

CREATE TABLE "post" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" varchar(128) NOT NULL,
  "user_id" INTEGER,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
-- @tps id n
-- @tps title s128
-- @tps user_id n
CREATE INDEX "idx_post_user_id" ON "post" ("user_id");


COMMIT;
