-- Migration: schema diff
-- Generated by zig-typespec migrate

BEGIN;

CREATE TABLE "post" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" varchar(128) NOT NULL
);
-- @tps id n
-- @tps title s128


ALTER TABLE "user"
-- WARNING: MODIFY COLUMN not supported in SQLite; requires table recreation
;
COMMIT;
