-- Migration: schema diff
-- Generated by zig-typespec migrate

BEGIN;

CREATE TABLE `post` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `title` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE `user`
MODIFY COLUMN `name` varchar(64) NOT NULL;
COMMIT;
