-- Migration: schema diff
-- Generated by rune migrate

BEGIN;

CREATE TABLE `post` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `title` varchar(128) NOT NULL,
  `user_id` int,
  INDEX `idx_user_id` (`user_id`),
  FOREIGN KEY (`user_id`) REFERENCES `user`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


COMMIT;
