-- Migration: schema diff
-- Generated by zig-typespec migrate

BEGIN;

CREATE TABLE `post` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `title` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ALTER TABLE `user` (drop and recreate)
DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

COMMIT;
