-- Migration: schema diff
-- Generated by zig-typespec migrate

BEGIN;

ALTER TABLE "user"
CREATE UNIQUE INDEX IF NOT EXISTS "uk_uk_email" ON "user" ("email"),
CREATE INDEX IF NOT EXISTS "idx_idx_name" ON "user" ("name");
COMMIT;
