-- Migration: schema diff
-- Generated by zig-typespec migrate

BEGIN;

CREATE TABLE `post` (
  `id` ª,
  `title` varchar(128) NOT NULL,
  `user_id` int,
  INDEX `idx_user_id` (`user_id`),
  FOREIGN KEY (`user_id`) REFERENCES `user`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


COMMIT;
