-- Generated by rune

CREATE DATABASE "mydb" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(64) NOT NULL
);

CREATE TABLE "post" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "title" varchar(128) NOT NULL
);
