-- Generated by zig-typespec

CREATE TABLE "accounts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "balance" NUMERIC(16, 2) NOT NULL,
  "contact" varchar(128) NOT NULL,
  "name" varchar(32) NOT NULL
);
-- @tps id n
-- @tps balance 16,2
-- @tps contact s128
-- @tps name s32
