-- Generated by rune

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" varchar(32) NOT NULL
);
-- @tps id n
-- @tps name s32

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_no" varchar(64) NOT NULL,
  "user_id" INTEGER,
  "amount" NUMERIC(16, 2),
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
-- @tps id n
-- @tps order_no s64
-- @tps user_id n
-- @tps amount m
CREATE INDEX "idx_user_id" ON "order" ("user_id");
