-- Generated by zig-typespec

CREATE TABLE "customer" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "email" varchar(128) NOT NULL,
  UNIQUE ("email")
);

CREATE TABLE "product" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "price" NUMERIC NOT NULL
);

CREATE TABLE "order_item" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "customer_id" INTEGER,
  "product_id" INTEGER,
  "quantity" INTEGER NOT NULL
);
