-- Generated by zig-typespec

CREATE TABLE "products" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "price" NUMERIC,
  "big_p" NUMERIC,
  "amt" NUMERIC(10, 2)
);
-- @tps id n
-- @tps price m
-- @tps big_p M
-- @tps amt 10,2
