-- Generated by rune

CREATE TABLE "events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT NOT NULL,
  "created_at" TEXT,
  "updated_at" TEXT,
  "payload" TEXT
);
-- @tps id n
-- @tps created_at t
-- @tps updated_at t
-- @tps payload j
