-- Generated by zig-typespec

CREATE TABLE "counters" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "small_u" INTEGER,
  "big_u" INTEGER,
  "plain_n" INTEGER,
  "unsigned" INTEGER
);
-- @tps id n
-- @tps small_u n
-- @tps big_u N
-- @tps plain_n n
