-- Generated by rune

CREATE TABLE "attachments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "content" BLOB,
  "avatar" BLOB
);
-- @sym id n
-- @sym content B
-- @sym avatar B
