-- Generated by rune

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
);
-- @sym id n

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER NOT NULL,
  "amount" NUMERIC(16, 2) NOT NULL,
  "created" TEXT,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
-- @sym id n
-- @sym user_id n
-- @sym amount m
-- @sym created t
