-- Generated by rune

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" varchar(32) NOT NULL,
  "email" varchar(128) NOT NULL
);
-- User account table
-- @sym id n
-- @sym name s32
-- @sym email s128
