-- Generated by rune

CREATE TABLE "flags" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "is_admin" INTEGER,
  "active" INTEGER,
  "enabled" INTEGER
);
-- @sym id n
-- @sym is_admin b
-- @sym active b
-- @sym enabled b
