-- Generated by rune

CREATE TABLE "documents" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT NOT NULL,
  "body" TEXT,
  "bio" TEXT,
  "short" varchar(64)
);
-- @sym id n
-- @sym body S
-- @sym bio S
-- @sym short s64
