-- Generated by rune

CREATE TABLE "mid" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" varchar(32) NOT NULL
);
-- user
-- @tps id n
-- @tps name s32

CREATE TABLE "mid" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "amount" NUMERIC(16, 2)
);
-- order
-- @tps id n
-- @tps amount m
