-- Generated by zig-typespec

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" varchar(32) NOT NULL,
  "email" varchar(128) NOT NULL,
  "balance" NUMERIC DEFAULT 0,
  "status" integer DEFAULT 0,
  "create_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("email")
);
-- 用户表
-- @tps id n
-- @tps name s32
-- @tps email s128
-- @tps balance m
-- @tps create_at t

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_no" varchar(64) NOT NULL,
  "user_id" INTEGER,
  "amount" NUMERIC NOT NULL,
  "status" integer DEFAULT 0,
  "create_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
-- 订单表
-- order.user_id: 下单用户
-- @tps id n
-- @tps order_no s64
-- @tps user_id n
-- @tps amount m
-- @tps create_at t
