-- Generated by rune

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" varchar(32) NOT NULL,
  "email" varchar(128) NOT NULL
);
-- User account table
-- @tps id n
-- @tps name s32
-- @tps email s128
