-- Generated by rune

CREATE TABLE "scores" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "value" INTEGER NOT NULL CHECK (value BETWEEN 0 AND 100),
  "grade" TEXT NOT NULL CHECK (grade IN ('A', 'B', 'C', 'D', 'F')),
  "ratio" NUMERIC(16, 2) NOT NULL CHECK (ratio > 0)
);
-- @tps id n
-- @tps value n
-- @tps ratio m
