-- Generated by rune

CREATE TABLE "logs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "level" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "ts" TEXT,
  UNIQUE ("ts")
);
-- @tps id n
-- @tps ts t
CREATE INDEX "idx_level" ON "logs" ("level");
