-- Generated by rune

CREATE TABLE "accounts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "balance" NUMERIC(16, 2) NOT NULL,
  "contact" varchar(128) NOT NULL,
  "name" varchar(32) NOT NULL
);
-- @sym id n
-- @sym balance 16,2
-- @sym contact s128
-- @sym name s32
