-- Generated by rune

CREATE TABLE "events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT NOT NULL,
  "created_at" TEXT,
  "updated_at" TEXT,
  "payload" TEXT
);
-- @sym id n
-- @sym created_at t
-- @sym updated_at t
-- @sym payload j
