-- Generated by zig-typespec

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" varchar(32) NOT NULL,
  "email" varchar(128) NOT NULL,
  "balance" NUMERIC DEFAULT 0,
  "status" integer DEFAULT 0,
  "create_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("email")
);
-- 用户表

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_no" varchar(64) NOT NULL,
  "user_id" INTEGER,
  "amount" NUMERIC NOT NULL,
  "status" integer DEFAULT 0,
  "create_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
-- 订单表
-- order.user_id: 下单用户
