-- Generated by zig-typespec

CREATE TABLE "attachments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "content" BLOB,
  "avatar" BLOB
);
-- @tps id n
-- @tps content B
-- @tps avatar B
