-- Generated by rune

CREATE TABLE "post" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ts" TEXT,
  "title" TEXT NOT NULL,
  "content" TEXT
);
-- @sym id n
-- @sym ts t
-- @sym content S

CREATE TABLE "comment" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ts" TEXT,
  "text" TEXT NOT NULL,
  "post_id" INTEGER NOT NULL
);
-- @sym id n
-- @sym ts t
-- @sym text S
-- @sym post_id n
