-- Generated by rune

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER NOT NULL,
  "amount" NUMERIC(16, 2) NOT NULL,
  "created" TEXT,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
-- @tps id n
-- @tps user_id n
-- @tps amount m
-- @tps created t
