-- Generated by rune

CREATE TABLE "products" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "price" NUMERIC(16, 2),
  "big_p" NUMERIC(20, 6),
  "amt" NUMERIC(10, 2)
);
-- @sym id n
-- @sym price m
-- @sym big_p M
-- @sym amt 10,2
