-- Generated by rune

CREATE TABLE "flags" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "is_admin" INTEGER,
  "active" INTEGER,
  "enabled" INTEGER
);
-- @tps id n
-- @tps is_admin b
-- @tps active b
-- @tps enabled b
