-- Generated by rune

CREATE TABLE "post" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ts" TEXT,
  "title" TEXT NOT NULL,
  "content" TEXT
);
-- @tps id n
-- @tps ts t
-- @tps content S

CREATE TABLE "comment" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ts" TEXT,
  "text" TEXT NOT NULL,
  "post_id" INTEGER NOT NULL
);
-- @tps id n
-- @tps ts t
-- @tps text S
-- @tps post_id n
