-- Generated by rune

CREATE TABLE "explicit" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "cnt" INTEGER,
  "amt" NUMERIC(10, 2),
  "code" varchar(64),
  "ver" INTEGER,
  "bigamt" NUMERIC(20, 6)
);
-- @sym id n
-- @sym amt 10,2
-- @sym code s64
-- @sym ver N
-- @sym bigamt 20,6
