-- Generated by rune

CREATE TABLE "customer" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "email" varchar(128) NOT NULL,
  UNIQUE ("email")
);
-- @tps id n
-- @tps email s128

CREATE TABLE "product" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "price" NUMERIC(16, 2) NOT NULL
);
-- @tps id n
-- @tps price m

CREATE TABLE "order_item" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "customer_id" INTEGER,
  "product_id" INTEGER,
  "quantity" INTEGER NOT NULL
);
-- @tps id n
-- @tps customer_id n
-- @tps product_id n
-- @tps quantity n
