-- Generated by rune

CREATE TABLE "counters" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "small_u" INTEGER,
  "big_u" INTEGER,
  "plain_n" INTEGER,
  "small_un" INTEGER
);
-- @sym id n
-- @sym small_u +n
-- @sym big_u +N
-- @sym plain_n n
-- @sym small_un +i
