-- Generated by zig-typespec

CREATE TABLE "explicit" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "cnt" integer,
  "amt" NUMERIC(10, 2),
  "code" varchar(64),
  "ver" INTEGER,
  "bigamt" NUMERIC(20, 6)
);
-- @tps id n
-- @tps amt 10,2
-- @tps code s64
-- @tps ver N
-- @tps bigamt 20,6
