-- Generated by zig-typespec

CREATE TABLE "logs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "level" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "ts" TEXT,
  UNIQUE ("ts")
);
CREATE INDEX "idx_level" ON "logs" ("level");
