-- Generated by rune

CREATE TABLE "documents" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT NOT NULL,
  "body" TEXT,
  "bio" TEXT,
  "short" varchar(64)
);
-- @tps id n
-- @tps body S
-- @tps bio S
-- @tps short s64
