-- Generated by rune

CREATE TABLE "user_role" (
  "user_id" INTEGER NOT NULL PRIMARY KEY,
  "role_id" INTEGER NOT NULL PRIMARY KEY,
  "granted" TEXT
);
-- @tps user_id n
-- @tps role_id n
-- @tps granted t
