-- Generated by zig-typespec

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" varchar(32) NOT NULL
);
-- @tps id n
-- @tps name s32

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER,
  "amount" NUMERIC(16, 2),
  FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE
);
-- @tps id n
-- @tps user_id n
-- @tps amount m

CREATE TABLE "log" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_id" INTEGER,
  FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE SET NULL
);
-- @tps id n
-- @tps order_id n
