const std = @import("std");
const ast_mod = @import("ast.zig");
const dialect_mod = @import("dialect.zig");
const dialect_enum = @import("dialect_enum.zig");
const typed_ast_mod = @import("typed_ast.zig");
const columns_mod = @import("codegen_columns.zig");
const indexes_mod = @import("codegen_indexes.zig");
const CheckConstraint = ast_mod.CheckConstraint;
const Writer = std.Io.Writer;

pub const Dialect = dialect_enum.Dialect;

pub const Codegen = struct {
    alloc: std.mem.Allocator,
    dialect: Dialect,
    backend: dialect_mod.DialectBackend,

    pub fn init(alloc: std.mem.Allocator, dialect: Dialect) Codegen {
        return .{
            .alloc = alloc,
            .dialect = dialect,
            .backend = dialect_mod.getBackend(dialect),
        };
    }

    // ─── TypedAst API (sole codegen path) ───────────────────────

    pub fn generateFromTypedAst(self: *Codegen, typed: typed_ast_mod.TypedAst) ![]const u8 {
        var aw = std.Io.Writer.Allocating.init(self.alloc);
        const w = &aw.writer;

        try w.writeAll("-- Generated by rune\n\n");

        if (typed.schema_name) |name| {
            if (self.backend.emitCreateDatabase) |emit| {
                try emit(w, name, typed.schema_charset);
            }
        }

        // Interleave tables, views, and sql_comments by line number
        var ti: usize = 0;
        var vi: usize = 0;
        var ci: usize = 0;
        while (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
            const table_line = if (ti < typed.tables.len) typed.tables[ti].line_no else std.math.maxInt(usize);
            const view_line = if (vi < typed.views.len) typed.views[vi].line_no else std.math.maxInt(usize);
            const comment_line = if (ci < typed.sql_comments.len) typed.sql_comments[ci].line_no else std.math.maxInt(usize);

            const min_line = @min(table_line, view_line, comment_line);

            if (comment_line == min_line) {
                try w.writeAll(typed.sql_comments[ci].text);
                try w.writeAll("\n");
                ci += 1;
            } else if (view_line == min_line) {
                try self.generateTypedView(w, typed.views[vi]);
                vi += 1;
                if (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
                    try w.writeAll("\n");
                }
            } else if (table_line == min_line) {
                try self.generateTypedTable(w, typed.tables[ti]);
                ti += 1;
                if (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
                    try w.writeAll("\n");
                }
            }
        }

        try w.flush();
        var out = aw.toArrayList();
        return try out.toOwnedSlice(self.alloc);
    }

    pub fn generateSingleTypedTable(self: *Codegen, table: typed_ast_mod.TypedTable) ![]const u8 {
        var aw = std.Io.Writer.Allocating.init(self.alloc);
        const w = &aw.writer;
        try self.generateTypedTable(w, table);
        try w.flush();
        var out = aw.toArrayList();
        return try out.toOwnedSlice(self.alloc);
    }

    /// Emit a full CREATE TABLE statement for one table to the given writer.
    /// Used by both forward codegen (generateFromTypedAst) and migration generation.
    pub fn generateTypedTable(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable) !void {
        try w.writeAll("CREATE TABLE ");
        try self.backend.quoteIdent(w, table.name);
        try w.writeAll(" (\n");

        var needs_comma = false;

        try emitColumnDefs(self, w, table, &needs_comma);
        try indexes_mod.emitInlineIndexes(self.backend, w, table, &needs_comma);
        for (table.indexes) |idx| {
            try self.backend.emitIndex(w, idx, &needs_comma);
        }
        try emitConstraints(self, w, table, &needs_comma);

        if (needs_comma) try w.writeAll("\n");

        try self.backend.emitTableFooter(w, table.engine, null, table.comment);
        try emitTableMetadata(self, w, table);
        try indexes_mod.emitStandaloneIndexes(self.backend, w, table);
        try indexes_mod.emitInlineColumnStandaloneIndexes(self.backend, w, table);
    }

    fn emitColumnDefs(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable, needs_comma: *bool) !void {
        for (table.columns) |col| {
            if (needs_comma.*) try w.writeAll(",\n");
            needs_comma.* = true;
            try w.writeAll("  ");
            try columns_mod.emitColumnDef(self.backend, w, col);
        }
    }

    fn emitConstraints(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable, needs_comma: *bool) !void {
        for (table.fks) |fk| {
            if (needs_comma.*) try w.writeAll(",\n");
            needs_comma.* = true;
            try w.writeAll("  ");
            try self.backend.emitForeignKey(w, fk);
        }
    }

    fn emitTableMetadata(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable) !void {
        if (table.comment) |c| {
            try self.backend.emitTableComment(w, table.name, c);
        }
        for (table.columns) |col| {
            if (col.comment) |c| {
                try self.backend.emitColumnComment(w, table.name, col.name, c);
            }
        }
        for (table.columns) |col| {
            if (col.sym_type) |sym| {
                if (self.backend.emitTypeMetadata) |emit| {
                    try emit(w, col.name, sym);
                }
            }
        }
    }

    /// Emit a CREATE VIEW statement.
    pub fn generateTypedView(self: Codegen, w: *Writer, view: typed_ast_mod.TypedView) !void {
        try self.backend.emitCreateView(w, view.name, view.query);
        if (view.comment) |c| {
            try self.backend.emitTableComment(w, view.name, c);
        }
    }

    /// Render a single column definition (shared by CREATE TABLE and ALTER TABLE paths).
    /// When skip_name is true, the column name is not emitted (used by PG ALTER COLUMN TYPE).
    pub fn emitColumnDef(self: Codegen, w: *Writer, col: typed_ast_mod.TypedColumn) !void {
        return columns_mod.emitColumnDef(self.backend, w, col);
    }

    pub fn emitColumnDefEx(self: Codegen, w: *Writer, col: typed_ast_mod.TypedColumn, skip_name: bool) !void {
        return columns_mod.emitColumnDefEx(self.backend, w, col, skip_name);
    }

    pub fn generateCheckExpr(self: Codegen, w: *Writer, field_name: []const u8, ck: CheckConstraint) !void {
        _ = self;
        try dialect_mod.emitCheckExpr(w, field_name, ck);
    }
};

// ─── Diagnostic ──────────────────────────────────────────────

pub fn diagnosticTrace(sql: []const u8) void {
    std.debug.print("=== [Stage 4: Codegen] ===\n\n", .{});

    var table_count: usize = 0;
    var field_count: usize = 0;
    var fk_count: usize = 0;
    var index_count: usize = 0;

    var line_it = std.mem.splitScalar(u8, sql, '\n');
    while (line_it.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (std.mem.startsWith(u8, trimmed, "CREATE TABLE ")) {
            table_count += 1;
        } else if (trimmed.len > 0 and trimmed[0] == '`' and std.mem.indexOf(u8, trimmed, "PRIMARY KEY") != null) {
            // Skip PRIMARY KEY lines
        } else if (std.mem.indexOf(u8, trimmed, "FOREIGN KEY") != null) {
            fk_count += 1;
        } else if (std.mem.indexOf(u8, trimmed, "INDEX") != null or std.mem.indexOf(u8, trimmed, "UNIQUE INDEX") != null or std.mem.indexOf(u8, trimmed, "FULLTEXT INDEX") != null) {
            index_count += 1;
        }
    }

    var col_it = std.mem.splitScalar(u8, sql, '\n');
    while (col_it.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len > 0 and trimmed[0] == '`') {
            field_count += 1;
        }
    }

    std.debug.print("Tables:    {d}\n", .{table_count});
    std.debug.print("Columns:   {d}\n", .{field_count});
    std.debug.print("FKs:       {d}\n", .{fk_count});
    std.debug.print("Indexes:   {d}\n", .{index_count});
    std.debug.print("SQL lines: {d}\n", .{std.mem.count(u8, sql, "\n") + 1});
    std.debug.print("SQL bytes: {d}\n\n", .{sql.len});
}

