const std = @import("std");
const diff_mod = @import("diff.zig");
const ast_mod = @import("ast.zig");
const codegen = @import("codegen.zig");
const typed_ast = @import("typed_ast.zig");
const dialect_mod = @import("dialect.zig");
const dialect_enum = @import("dialect_enum.zig");
const utils = @import("utils.zig");
const Field = ast_mod.Field;
const TypeInfo = ast_mod.TypeInfo;

const Dialect = dialect_enum.Dialect;

// ─── Helpers ───────────────────────────────────────────────

const optionalStrEq = utils.optionalStrEq;

fn emitComma(w: anytype, needs_comma: *bool) !void {
    if (needs_comma.*) try w.writeAll(",\n");
    needs_comma.* = true;
}

fn beginAlterTable(w: anytype, backend: dialect_mod.DialectBackend, table_name: []const u8, table_has_ops: *bool) !void {
    if (!table_has_ops.*) {
        try w.writeAll("ALTER TABLE ");
        try backend.quoteIdent(w, table_name);
        try w.writeAll("\n");
        table_has_ops.* = true;
    }
}

// ─── generateFromDiff (orchestrator) ─────────────────────────

pub fn generateFromDiff(
    alloc: std.mem.Allocator,
    d: diff_mod.SchemaDiff,
    new_typed: typed_ast.TypedAst,
    new_resolved: ast_mod.ResolvedAst,
    dialect: Dialect,
) ![]const u8 {
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    try w.writeAll("-- Migration: schema diff\n");
    try w.writeAll("-- Generated by rune migrate\n\n");
    try w.writeAll("BEGIN;\n\n");

    var has_operations = false;

    try emitDroppedTables(w, dialect_mod.getBackend(dialect), d.dropped_tables);
    if (d.dropped_tables.len > 0) has_operations = true;

    try emitViewDiffs(w, dialect_mod.getBackend(dialect), d.view_diffs, new_typed);
    if (d.view_diffs.len > 0) has_operations = true;

    try emitTableDiffs(alloc, w, d.table_diffs, new_resolved, dialect, &has_operations);

    try w.writeAll("COMMIT;\n");

    try w.flush();
    var out = aw.toArrayList();
    return try out.toOwnedSlice(alloc);
}

// ─── generateFromDiff sub-functions ────────────────────────────

fn emitDroppedTables(w: anytype, backend: dialect_mod.DialectBackend, dropped: []const []const u8) !void {
    for (dropped) |tname| {
        try w.writeAll("DROP TABLE IF EXISTS ");
        try backend.quoteIdent(w, tname);
        try w.writeAll(";\n\n");
    }
}

fn emitViewDiffs(w: anytype, backend: dialect_mod.DialectBackend, view_diffs: []const diff_mod.ViewDiff, new_typed: typed_ast.TypedAst) !void {
    for (view_diffs) |vd| {
        switch (vd.action) {
            .drop => {
                try w.writeAll("DROP VIEW IF EXISTS ");
                try backend.quoteIdent(w, vd.name);
                try w.writeAll(";\n\n");
            },
            .create, .modify => {
                if (vd.action == .modify) {
                    try w.writeAll("DROP VIEW IF EXISTS ");
                    try backend.quoteIdent(w, vd.name);
                    try w.writeAll(";\n\n");
                }
                if (findTypedView(new_typed, vd.name)) |view| {
                    try backend.emitCreateView(w, view.name, view.query);
                    try w.writeAll("\n");
                }
            },
        }
    }
}

fn emitTableDiffs(
    alloc: std.mem.Allocator,
    w: anytype,
    table_diffs: []const diff_mod.TableDiff,
    new_resolved: ast_mod.ResolvedAst,
    dialect: Dialect,
    has_operations: *bool,
) !void {
    var tr = typed_ast.TypeResolver.init(alloc);
    var cg = codegen.Codegen.init(alloc, dialect);
    const backend = dialect_mod.getBackend(dialect);

    for (table_diffs) |td| {
        switch (td.action) {
            .create => {
                has_operations.* = true;
                if (findResolvedTable(new_resolved, td.name)) |table| {
                    var single_tables = try std.ArrayList(ast_mod.ResolvedTable).initCapacity(alloc, 1);
                    try single_tables.append(alloc, table);
                    const single_resolved = ast_mod.ResolvedAst{
                        .schema_name = new_resolved.schema_name,
                        .schema_charset = new_resolved.schema_charset,
                        .custom_types = new_resolved.custom_types,
                        .tables = try single_tables.toOwnedSlice(alloc),
                        .views = &.{},
                        .sql_comments = &.{},
                    };
                    const single_typed = try tr.resolve(single_resolved, dialect);
                    if (single_typed.tables.len > 0) {
                        try cg.generateTypedTable(w, single_typed.tables[0]);
                    }
                    try w.writeAll("\n\n");
                }
            },
            .alter => {
                var table_has_ops = false;
                var sub_needs_comma = false;

                try emitFieldDiffs(w, backend, td, &tr, &cg, dialect, new_resolved, &table_has_ops, &sub_needs_comma);
                try emitIndexDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);
                try emitMetadataDiffs(w, backend, td, &table_has_ops, &sub_needs_comma, has_operations);
                try emitFkDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);

                if (table_has_ops) {
                    has_operations.* = true;
                    try w.writeAll(";\n");
                }
            },
        }
    }
}

fn emitFieldDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    tr: *typed_ast.TypeResolver,
    cg: *codegen.Codegen,
    dialect: Dialect,
    new_resolved: ast_mod.ResolvedAst,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.field_diffs) |fd| {
        switch (fd.action) {
            .add => {
                try beginAlterTable(w, backend, td.name, table_has_ops);
                if (fd.new_field) |nf| {
                    try emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD COLUMN ");
                    const typed_col = try tr.resolveColumn(nf, dialect, new_resolved.custom_types);
                    try cg.emitColumnDef(w, typed_col);
                }
            },
            .drop => {
                try beginAlterTable(w, backend, td.name, table_has_ops);
                try emitComma(w, sub_needs_comma);
                try backend.emitAlterDropColumn(w, fd.name);
            },
            .modify => {
                try beginAlterTable(w, backend, td.name, table_has_ops);
                if (fd.new_field) |nf| {
                    try emitComma(w, sub_needs_comma);
                    try backend.emitAlterModifyColumn(w, nf.name);
                    if (backend.modify_needs_column_def) {
                        const typed_col = try tr.resolveColumn(nf, dialect, new_resolved.custom_types);
                        try cg.emitColumnDefEx(w, typed_col, backend.modify_column_def_skips_name);
                    }
                }
            },
            .rename => {
                try beginAlterTable(w, backend, td.name, table_has_ops);
                if (fd.rename_from) |old_name| {
                    try emitComma(w, sub_needs_comma);
                    try backend.emitAlterRenameColumn(w, old_name, fd.name);
                    if (backend.rename_needs_column_def) {
                        if (fd.new_field) |nf| {
                            const typed_col = try tr.resolveColumn(nf, dialect, new_resolved.custom_types);
                            try cg.emitColumnDef(w, typed_col);
                        }
                    }
                }
            },
        }
    }
}

fn emitIndexDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.index_diffs) |idx_diff| {
        switch (idx_diff.action) {
            .add => {
                if (idx_diff.new_idx) |idx| {
                    try beginAlterTable(w, backend, td.name, table_has_ops);
                    try emitComma(w, sub_needs_comma);
                    try backend.emitAlterAddIndex(w, td.name, idx);
                }
            },
            .drop => {
                if (idx_diff.old_idx) |idx| {
                    try beginAlterTable(w, backend, td.name, table_has_ops);
                    try emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropIndex(w, idx);
                }
            },
            .modify => {
                if (idx_diff.old_idx) |old_idx| {
                    try beginAlterTable(w, backend, td.name, table_has_ops);
                    try emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropIndex(w, old_idx);
                }
                if (idx_diff.new_idx) |new_idx| {
                    try beginAlterTable(w, backend, td.name, table_has_ops);
                    try emitComma(w, sub_needs_comma);
                    try backend.emitAlterAddIndex(w, td.name, new_idx);
                }
            },
        }
    }
}

fn emitMetadataDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
    has_operations: *bool,
) !void {
    if (td.metadata_diff) |md| {
        if (!optionalStrEq(md.old_comment, md.new_comment)) {
            if (md.new_comment) |nc| {
                const result = backend.commentResult();
                switch (result) {
                    .added_to_alter => {
                        try beginAlterTable(w, backend, td.name, table_has_ops);
                        try emitComma(w, sub_needs_comma);
                        try backend.emitAlterTableComment(w, td.name, nc);
                    },
                    .standalone_emitted => {
                        if (table_has_ops.*) {
                            try w.writeAll(";\n\n");
                            table_has_ops.* = false;
                            sub_needs_comma.* = false;
                        }
                        try backend.emitAlterTableComment(w, td.name, nc);
                        has_operations.* = true;
                    },
                    .unsupported => {
                        try beginAlterTable(w, backend, td.name, table_has_ops);
                        try emitComma(w, sub_needs_comma);
                        try backend.emitAlterTableComment(w, td.name, nc);
                    },
                }
            }
        }
        if (!optionalStrEq(md.old_engine, md.new_engine)) {
            try beginAlterTable(w, backend, td.name, table_has_ops);
            try emitComma(w, sub_needs_comma);
            try backend.emitAlterEngine(w, md.new_engine);
        }
    }
}

fn emitFkDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.fk_diffs) |fk_diff| {
        switch (fk_diff.action) {
            .add => {
                if (fk_diff.new_fk) |fk| {
                    try beginAlterTable(w, backend, td.name, table_has_ops);
                    try emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD ");
                    try backend.emitForeignKey(w, fk);
                }
            },
            .drop => {
                if (fk_diff.old_fk) |fk| {
                    try beginAlterTable(w, backend, td.name, table_has_ops);
                    try emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropFk(w, fk);
                }
            },
            .modify => {
                if (fk_diff.old_fk) |old_fk| {
                    try beginAlterTable(w, backend, td.name, table_has_ops);
                    try emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropFk(w, old_fk);
                }
                if (fk_diff.new_fk) |new_fk| {
                    try emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD ");
                    try backend.emitForeignKey(w, new_fk);
                }
            },
        }
    }
}

fn findResolvedTable(ast: ast_mod.ResolvedAst, name: []const u8) ?ast_mod.ResolvedTable {
    for (ast.tables) |table| {
        if (std.mem.eql(u8, table.name, name)) return table;
    }
    return null;
}

fn findTypedView(typed: typed_ast.TypedAst, name: []const u8) ?typed_ast.TypedView {
    for (typed.views) |view| {
        if (std.mem.eql(u8, view.name, name)) return view;
    }
    return null;
}

