-- Generated by zig-typespec

CREATE DATABASE `demo`;

CREATE TABLE `` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `username` varchar(32) NOT NULL,
  `email` varchar(128) NOT NULL,
  `age` int DEFAULT 0 CHECK (age BETWEEN 0 AND 150),
  `status` int(1) DEFAULT 0 CHECK (status IN (0,1,2)),
  `balance` decimal(16, 2) DEFAULT 0 CHECK (balance >= 0),
  `score` decimal(20, 6) DEFAULT 0 CHECK (score BETWEEN 0 AND 100),
  UNIQUE INDEX `uk_email` (`email`)
);

CREATE TABLE `` (
  `user_id` int,
  `role_id` int
);

CREATE TABLE `` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `order_no` varchar(64) NOT NULL,
  `user_id` int,
  `amount` decimal(16, 2) CHECK (amount > 0),
  `quantity` int DEFAULT 1 CHECK (quantity >= 1),
  `discount` decimal(20, 6) DEFAULT 0 CHECK (discount >= 0 AND discount <= 1),
  `type` varchar(32) CHECK (type IN ('standard','express','bulk')),
  FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE
);
