-- Generated by zig-typespec

CREATE DATABASE `demo`;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `deleted_at` datetime,
  `deleted_by` int,
  `version` bigint,
  `status` int(1) DEFAULT 0,
  `create_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `restore_token` varchar(64),
  `name` varchar(32) NOT NULL,
  `email` varchar(128) NOT NULL,
  COMMENT = '用户表'
);

CREATE TABLE `order` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `deleted_at` datetime,
  `deleted_by` int,
  `version` bigint,
  `status` int(1) DEFAULT 0,
  `create_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `order_no` varchar(64) NOT NULL,
  `amount` decimal(16, 2) NOT NULL,
  COMMENT = '订单表'
);
