-- Generated by zig-typespec

CREATE DATABASE `ecommerce`;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `version` bigint,
  `status` int(1) DEFAULT 0,
  `delete_at` datetime,
  `create_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` varchar(32) NOT NULL,
  `email` varchar(128) NOT NULL,
  `password` varchar(256) NOT NULL,
  `avatar` text,
  `is_admin` boolean DEFAULT 0,
  `balance` decimal(16, 2) DEFAULT 0,
  `settings` json,
  UNIQUE INDEX `uk_email` (`email`),
  INDEX `idx_name` (`name`),
  COMMENT = '用户表'
);

CREATE TABLE `product` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `version` bigint,
  `status` int(1) DEFAULT 0,
  `delete_at` datetime,
  `create_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` varchar(128) NOT NULL,
  `description` text,
  `price` decimal(16, 2) NOT NULL,
  `stock` int DEFAULT 0,
  `category_id` int,
  INDEX `idx_category_id` (`category_id`),
  INDEX `idx_price` (`price`),
  COMMENT = '商品表'
);

CREATE TABLE `order` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `version` bigint,
  `status` int(1) DEFAULT 0,
  `delete_at` datetime,
  `create_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `order_no` varchar(64) NOT NULL,
  `user_id` int,
  `amount` decimal(16, 2) NOT NULL,
  `discount` decimal(20, 6) DEFAULT 0,
  `note` varchar(512),
  `paid_on` date,
  FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE,
  UNIQUE INDEX `uk_order_no` (`order_no`),
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_paid_on` (`paid_on`),
  COMMENT = '订单表'
);
